In [101]:
import requests
import pandas as pd
import os

# Corrected Overpass query for Spätis/corner stores
query = """
[out:json];
(
node[shop=convenience](52.4,13.2,52.7,13.6);
  node[shop=kiosk](52.4,13.2,52.7,13.6);
);
out;
"""

url = "https://overpass-api.de/api/interpreter"

response = requests.post(url, data=query)

if response.status_code == 200:
    try:
        data = response.json()
        elements = data.get("elements", [])
        df = pd.json_normalize(elements)

        # Save CSV to Documents
        folder = "/Users/harrisongoodman/Documents"
        os.makedirs(folder, exist_ok=True)
        file_path = os.path.join(folder, "spatis.csv")
        df.to_csv(file_path, index=False)
        print(f"CSV saved successfully to: {file_path}")

    except ValueError:
        print("Response is not in JSON format:")
        print(response.text[:200])
else:
    print(f"Request failed with status code: {response.status_code}")

CSV saved successfully to: /Users/harrisongoodman/Documents/spatis.csv

In [83]:
# Suppose your GeoDataFrame is called spatis_gdf
column_names = spatis_gdf.columns.to_list()
# Display all column names
print(column_names)

['geometry', 'addr:city', 'addr:country', 'addr:housenumber', 'addr:postcode', 'addr:street', 'addr:suburb', 'amenity', 'check_date:opening_hours', 'compressed_air', 'fuel:adblue', 'fuel:biodiesel', 'fuel:diesel', 'fuel:e10', 'fuel:octane_95', 'fuel:octane_98', 'name', 'opening_hours', 'operator', 'shop', 'wheelchair', 'brand', 'brand:wikidata', 'brand:wikipedia', 'fuel:GTL_diesel', 'fuel:biogas', 'fuel:cng', 'fuel:lpg', 'fuel:octane_102', 'surveillance', 'website', 'check_date', 'created_by', 'dog', 'email', 'fax', 'phone', 'start_date', 'indoor_seating', 'organic', 'outdoor_seating', 'smoking', 'opening_hours:signed', 'diet:halal', 'level', 'payment:credit_cards', 'payment:debit_cards', 'payment:apple_pay', 'payment:cards', 'payment:cash', 'payment:google_pay', 'payment:paypal', 'drink:club-mate', 'entrance', 'craft', 'post_office', 'post_office:brand', 'post_office:brand:wikidata', 'post_office:service_provider', 'name:signed', 'toilets:wheelchair', 'wheelchair:description', 'noname', 'lottery', 'post_office:ref', 'origin', 'alt_name', 'cuisine', 'ref:vatin', 'name:de', 'name:en', 'addr:floor', 'air_conditioning', 'contact:instagram', 'contact:website', 'internet_access', 'stroller', 'toilets', 'access:covid19', 'delivery:covid19', 'post_office:type', 'contact:fax', 'contact:phone', 'name:ru', 'opening_hours:covid19', 'takeaway:covid19', 'internet_access:fee', 'atm', 'atm:operator', 'note:de', 'ref:Hermes', 'description', 'coffee', 'tobacco', 'note', 'operator:wikidata', 'ref', 'currency:EUR', 'source', 'diet:gluten_free', 'leisure', 'cafe', 'payment:coins', 'vending:sweets', 'vending:toys', 'service:phone', 'type', 'diet:kosher', 'diet:vegetarian', 'post_box', 'operator:wikipedia', 'changing_table', 'payment:mastercard', 'payment:visa', 'second_hand', 'toilets:menstrual_products', 'takeaway', 'toilets:access', 'parcel_pickup', 'drink:coffee', 'sells:tobacco', 'name:zh', 'addr:housename', 'fixme', 'description:payment', 'payment:cards:min_payment', 'post_office:parcel_from', 'post_office:parcel_to', 'contact:mobile', 'dry_cleaning', 'ice_cream', 'drink:beer', 'tickets:public_transport', 'diet:vegan', 'branch', 'bulk_purchase', 'diet:organic', 'frozen_yogurt', 'reusable_packaging:offer', 'contact:email', 'lgbtq', 'post_office:letter', 'fuel:HGV_diesel', 'fuel:octane_100', 'addr:place', 'post_office:parcel_pickup', 'ref:deutsche_post', 'tourism', 'fair_trade', 'payment:contactless', 'payment:maestro', 'payment:v_pay', 'payment:app', 'mapillary', 'opening_date', 'post_office:operator', 'payment:others', 'cash_in', 'survey:date', 'post_office:letter_from', 'post_office:packaging', 'post_office:stamps', 'payment:girocard', 'description:en', 'old_name', 'car_repair', 'car_wash', 'old_addr:housenumber', 'old_addr:street', 'contact:facebook', 'reusable_packaging:accept', 'wikidata', 'wikipedia', 'zero_waste', 'not:brand:wikidata', 'post_office:post_bank', 'building', 'roof:material', 'roof:shape', 'vending', 'layer', 'disused:shop', 'service:copy', 'service:fax', 'service:scan', 'self_checkout', 'payment:american_express', 'payment:notes', 'payment:telephone_cards', 'payment:credit_cards:min_payment', 'loc_name', 'delivery', 'bicycle', 'indoor:level', 'name:bg', 'name:fa', 'ramp:wheelchair', 'toilets:charge', 'smoking:outside', 'description:name', 'name:ar', 'post_office:service_provider:wikidata', 'wheelchair:description:de', 'wheelchair:description:en', 'payment:account_cards', 'payment:alipay', 'payment:bancomat', 'payment:blik', 'payment:cheque', 'payment:clipper', 'payment:cryptocurrencies', 'payment:diners_club', 'payment:discover_card', 'payment:dkv', 'payment:electronic_purses', 'payment:ep_easycard', 'payment:ep_geldkarte', 'payment:ep_ipass', 'payment:jcb', 'payment:mastercard_contactless', 'payment:prepaid_ticket', 'payment:unionpay', 'payment:uta', 'payment:visa_debit', 'payment:visa_electron', 'payment:wechat', 'check_date:currency:XBT', 'currency:XBT', 'payment:lightning', 'payment:lightning_contactless', 'payment:onchain', 'description:de', 'payment:ec', 'payment:ec_cards', 'sells:lottery', 'sells:public_transport_tickets', 'description:pl', 'location', 'ref:DeutschePost', 'golf', 'cash_withdrawal:type', 'post_office:opening_hours', 'money_transfer', 'mobile', 'post_office:id_check', 'name:ko', 'public_transport', 'ticket', 'building:levels', 'roof:levels', 'nohousenumber', 'building:colour', 'building:material', 'facebook', 'access', 'indoor', 'room', 'height', 'building:part', 'name:ja', 'biergarten']

In [84]:
# Explore all columns in the Spätis GeoDataFrame
spatis_gdf.describe(include="all").T

                 count unique                            top freq
geometry           151    151  POINT (13.2961178 52.4993218)    1
addr:city           59      1                         Berlin   59
addr:country        39      1                             DE   39
addr:housenumber    82     59                             14    4
addr:postcode       65     47                          10827    3
...                ...    ...                            ...  ...
room                 0      0                            NaN  NaN
height               0      0                            NaN  NaN
building:part        0      0                            NaN  NaN
name:ja              0      0                            NaN  NaN
biergarten           0      0                            NaN  NaN

[261 rows x 4 columns]

In [103]:
# Count missing values in each column
missing_count = spatis_gdf.isna().sum().sort_values(ascending=False)

# Show columns that have more than 200 missing values
print(missing_count[missing_count > 200])

Series([], dtype: int64)

In [86]:
# check unique values in 'barand' column
spatis_gdf['brand'].value_counts()

Series([], Name: count, dtype: int64)

In [104]:
#expland all columns to see more details
pd.set_option('display.max_columns', None)
print(spatis_gd.head(3))

                                name brand       operator  \
element id
node    63253672           Späti Joe   NaN            NaN
        285096511  Späti am Comenius   NaN  H.Y. Soysüren
        427670051              Späti   NaN            NaN

                                addr:street addr:housenumber addr:postcode  \
element id
node    63253672   Joachim-Friedrich-Straße               39         10711
        285096511            Gubener Straße               43         10243
        427670051                       NaN              NaN           NaN

                      addr:suburb addr:city addr:country phone email website  \
element id
node    63253672         Halensee    Berlin           DE   NaN   NaN     NaN
        285096511  Friedrichshain    Berlin           DE   NaN   NaN     NaN
        427670051             NaN       NaN          NaN   NaN   NaN     NaN

                                                       opening_hours  \
element id
node    63253672                                                24/7
        285096511  Mo-Th 08:00-00:00, Fr 08:00-01:00, Sa 08:00-01...
        427670051                               PH,Mo-Su 06:00-24:00

                  payment:visa payment:mastercard payment:girocard delivery  \
element id
node    63253672           NaN                NaN              NaN      NaN
        285096511          NaN                NaN              NaN      NaN
        427670051          NaN                NaN              NaN      NaN

                  surveillance wheelchair building   latitude  longitude  \
element id
node    63253672           NaN        NaN      NaN  52.499322  13.296118
        285096511          NaN    limited      NaN  52.511469  13.449035
        427670051          NaN        NaN      NaN  52.512027  13.496422

                                    geometry source
element id
node    63253672   POINT (13.29612 52.49932)    NaN
        285096511  POINT (13.44904 52.51147)    NaN
        427670051  POINT (13.49642 52.51203)    NaN

In [105]:
# Selected Columns & Add Coordinates

In [89]:
import geopandas as gpd

# Example: Load your GeoDataFrame if not already loaded
# spatis_gdf = gpd.read_file("your_file.geojson")  # or .shp, etc.

# Ensure it's a GeoDataFrame
if not isinstance(spatis_gdf, gpd.GeoDataFrame):
    spatis_gdf = gpd.GeoDataFrame(spatis_gdf, geometry='geometry')

# Check the current CRS
print("Current CRS:", spatis_gdf.crs)

# Set CRS to WGS84 (lat/lon) if not already
spatis_gdf = spatis_gdf.to_crs(epsg=4326)

# Optional: Ensure geometry type is Point (needed for lat/lon extraction)
spatis_gdf = spatis_gdf[spatis_gdf.geometry.type == "Point"]

# Now you can extract lat/lon
spatis_gdf['latitude'] = spatis_gdf.geometry.y
spatis_gdf['longitude'] = spatis_gdf.geometry.x

# Quick check
print(spatis_gdf[['latitude', 'longitude']].head())

Current CRS: epsg:4326
                    latitude  longitude
element id
node    63253672   52.499322  13.296118
        285096511  52.511469  13.449035
        427670051  52.512027  13.496422
        427670057  52.512055  13.497071
        448594622  52.501098  13.441111

In [106]:
spatis_gdf['geometry'] = spatis_gdf['geometry'].apply(lambda geom: geom if geom.geom_type == 'Point' else geom.representative_point())
# Extract latitude and longitude
spatis_gdf["latitude"] = spatis_gdf.geometry.y
spatis_gdf["longitude"] = spatis_gdf.geometry.x
spatis_gdf

                                      geometry addr:city addr:country  \
element id
node    63253672     POINT (13.29612 52.49932)    Berlin           DE
        285096511    POINT (13.44904 52.51147)    Berlin           DE
        427670051    POINT (13.49642 52.51203)       NaN          NaN
        427670057    POINT (13.49707 52.51205)       NaN          NaN
        448594622     POINT (13.44111 52.5011)       NaN          NaN
...                                        ...       ...          ...
        12793386255  POINT (13.47928 52.50199)    Berlin          NaN
        12829967540  POINT (13.41345 52.54099)       NaN          NaN
        13148808097  POINT (13.47074 52.50639)       NaN          NaN
        13205182768  POINT (13.35372 52.49292)       NaN          NaN
        13302705766  POINT (13.38302 52.49293)       NaN          NaN

                    addr:housenumber addr:postcode               addr:street  \
element id
node    63253672                  39         10711  Joachim-Friedrich-Straße
        285096511                 43         10243            Gubener Straße
        427670051                NaN           NaN                       NaN
        427670057                243         10365         Frankfurter Allee
        448594622                NaN           NaN                       NaN
...                              ...           ...                       ...
        12793386255               17         10317             Nöldnerstraße
        12829967540                3           NaN           Danziger Straße
        13148808097              NaN           NaN                       NaN
        13205182768              NaN           NaN                       NaN
        13302705766              NaN           NaN                       NaN

                        addr:suburb amenity check_date:opening_hours  \
element id
node    63253672           Halensee     NaN                      NaN
        285096511    Friedrichshain     NaN                      NaN
        427670051               NaN     NaN                      NaN
        427670057               NaN     NaN                      NaN
        448594622               NaN     NaN               2024-03-29
...                             ...     ...                      ...
        12793386255             NaN     NaN                      NaN
        12829967540             NaN     NaN                      NaN
        13148808097             NaN     NaN                      NaN
        13205182768             NaN     NaN                      NaN
        13302705766             NaN     NaN                      NaN

                    compressed_air fuel:adblue fuel:biodiesel fuel:diesel  \
element id
node    63253672               NaN         NaN            NaN         NaN
        285096511              NaN         NaN            NaN         NaN
        427670051              NaN         NaN            NaN         NaN
        427670057              NaN         NaN            NaN         NaN
        448594622              NaN         NaN            NaN         NaN
...                            ...         ...            ...         ...
        12793386255            NaN         NaN            NaN         NaN
        12829967540            NaN         NaN            NaN         NaN
        13148808097            NaN         NaN            NaN         NaN
        13205182768            NaN         NaN            NaN         NaN
        13302705766            NaN         NaN            NaN         NaN

                    fuel:e10 fuel:octane_95 fuel:octane_98  \
element id
node    63253672         NaN            NaN            NaN
        285096511        NaN            NaN            NaN
        427670051        NaN            NaN            NaN
        427670057        NaN            NaN            NaN
        448594622        NaN            NaN            NaN
...                      ...            ...            ...
        12793386255      NaN            NaN            NaN
        12829967540      NaN            NaN            NaN
        13148808097      NaN            NaN            NaN
        13205182768      NaN            NaN            NaN
        13302705766      NaN            NaN            NaN

                                                   name  \
element id
node    63253672                              Späti Joe
        285096511                     Späti am Comenius
        427670051                                 Späti
        427670057       Sheran Späti + Hermes Paketshop
        448594622                      Späti am Schlesi
...                                                 ...
        12793386255  Confetti MiniMarket Spätkauf Späti
        12829967540                         Späti Gate1
        13148808097                               Späti
        13205182768                          Goltzspäti
        13302705766                     The Späti House

                                                         opening_hours  \
element id
node    63253672                                                  24/7
        285096511    Mo-Th 08:00-00:00, Fr 08:00-01:00, Sa 08:00-01...
        427670051                                 PH,Mo-Su 06:00-24:00
        427670057                                    Mo-Su 07:00-01:00
        448594622                                                  NaN
...                                                                ...
        12793386255                  Mo–Fr 11:00–21:00; So 12:00–21:00
        12829967540                                                NaN
        13148808097                                                NaN
        13205182768                                                NaN
        13302705766                                                NaN

                          operator         shop wheelchair brand  \
element id
node    63253672               NaN  convenience        NaN   NaN
        285096511    H.Y. Soysüren        kiosk    limited   NaN
        427670051              NaN  convenience        NaN   NaN
        427670057              NaN  convenience         no   NaN
        448594622              NaN  convenience         no   NaN
...                            ...          ...        ...   ...
        12793386255            NaN  convenience        NaN   NaN
        12829967540            NaN  convenience         no   NaN
        13148808097            NaN  convenience        NaN   NaN
        13205182768            NaN        kiosk        NaN   NaN
        13302705766            NaN  convenience         no   NaN

                    brand:wikidata brand:wikipedia fuel:GTL_diesel  \
element id
node    63253672               NaN             NaN             NaN
        285096511              NaN             NaN             NaN
        427670051              NaN             NaN             NaN
        427670057              NaN             NaN             NaN
        448594622              NaN             NaN             NaN
...                            ...             ...             ...
        12793386255            NaN             NaN             NaN
        12829967540            NaN             NaN             NaN
        13148808097            NaN             NaN             NaN
        13205182768            NaN             NaN             NaN
        13302705766            NaN             NaN             NaN

                    fuel:biogas fuel:cng fuel:lpg fuel:octane_102  \
element id
node    63253672            NaN      NaN      NaN             NaN
        285096511           NaN      NaN      NaN             NaN
        427670051           NaN      NaN      NaN             NaN
        427670057           NaN      NaN      NaN             NaN
        448594622           NaN      NaN      NaN             NaN
...                         ...      ...      ...             ...
        12793386255         NaN      NaN      NaN             NaN
        12829967540         NaN      NaN      NaN             NaN
        13148808097         NaN      NaN      NaN             NaN
        13205182768         NaN      NaN      NaN             NaN
        13302705766         NaN      NaN      NaN             NaN

                    surveillance website  check_date created_by  dog email  \
element id
node    63253672             NaN     NaN  2025-05-11        NaN  NaN   NaN
        285096511            NaN     NaN         NaN        NaN  NaN   NaN
        427670051            NaN     NaN         NaN        NaN  NaN   NaN
        427670057            NaN     NaN         NaN        NaN  NaN   NaN
        448594622            NaN     NaN  2024-12-23        NaN  NaN   NaN
...                          ...     ...         ...        ...  ...   ...
        12793386255          NaN     NaN         NaN        NaN  NaN   NaN
        12829967540          NaN     NaN  2025-05-10        NaN  NaN   NaN
        13148808097          NaN     NaN         NaN        NaN  NaN   NaN
        13205182768          NaN     NaN         NaN        NaN  NaN   NaN
        13302705766          NaN     NaN         NaN        NaN  NaN   NaN

                     fax          phone start_date indoor_seating organic  \
element id
node    63253672     NaN            NaN        NaN            NaN     NaN
        285096511    NaN            NaN        NaN            NaN     NaN
        427670051    NaN            NaN        NaN            NaN     NaN
        427670057    NaN            NaN        NaN            yes     NaN
        448594622    NaN            NaN        NaN            NaN     NaN
...                  ...            ...        ...            ...     ...
        12793386255  NaN  +493055631177        NaN            NaN     NaN
        12829967540  NaN            NaN        NaN            NaN     NaN
        13148808097  NaN            NaN        NaN            NaN     NaN
        13205182768  NaN            NaN        NaN            NaN     NaN
        13302705766  NaN            NaN        NaN            NaN     NaN

                    outdoor_seating smoking opening_hours:signed diet:halal  \
element id
node    63253672                NaN     NaN                  NaN        NaN
        285096511               NaN     NaN                  NaN        NaN
        427670051               NaN     NaN                  NaN        NaN
        427670057               yes     NaN                  NaN        NaN
        448594622          sidewalk     NaN                   no        NaN
...                             ...     ...                  ...        ...
        12793386255             NaN     NaN                  NaN        NaN
        12829967540             NaN     NaN                  NaN        NaN
        13148808097             NaN     NaN                  NaN        NaN
        13205182768             NaN     NaN                  NaN        NaN
        13302705766             NaN     NaN                  NaN        NaN

                    level payment:credit_cards payment:debit_cards  \
element id
node    63253672      NaN                  NaN                 NaN
        285096511     NaN                  NaN                 NaN
        427670051     NaN                  NaN                 NaN
        427670057     NaN                  NaN                 NaN
        448594622       0                  NaN                 NaN
...                   ...                  ...                 ...
        12793386255   NaN                  yes                 yes
        12829967540   NaN                  NaN                 NaN
        13148808097   NaN                  NaN                 NaN
        13205182768   NaN                  NaN                 NaN
        13302705766   NaN                  NaN                 NaN

                    payment:apple_pay payment:cards payment:cash  \
element id
node    63253672                  NaN           NaN          NaN
        285096511                 yes           yes          yes
        427670051                 NaN           NaN          NaN
        427670057                 NaN           NaN          NaN
        448594622                 NaN           NaN          NaN
...                               ...           ...          ...
        12793386255               NaN           NaN          NaN
        12829967540               NaN           NaN          NaN
        13148808097               NaN           NaN          NaN
        13205182768               NaN           NaN          NaN
        13302705766               NaN           NaN          NaN

                    payment:google_pay payment:paypal drink:club-mate  \
element id
node    63253672                   NaN            NaN             NaN
        285096511                  yes            yes             NaN
        427670051                  NaN            NaN             NaN
        427670057                  NaN            NaN             NaN
        448594622                  NaN            NaN             NaN
...                                ...            ...             ...
        12793386255                NaN            NaN             NaN
        12829967540                NaN            NaN             NaN
        13148808097                NaN            NaN             NaN
        13205182768                NaN            NaN             NaN
        13302705766                NaN            NaN             NaN

                    entrance craft post_office post_office:brand  \
element id
node    63253672         NaN   NaN         NaN               NaN
        285096511        NaN   NaN         NaN               NaN
        427670051        NaN   NaN         NaN               NaN
        427670057        NaN   NaN         NaN               NaN
        448594622        NaN   NaN         NaN               NaN
...                      ...   ...         ...               ...
        12793386255      NaN   NaN         NaN               NaN
        12829967540      NaN   NaN         NaN               NaN
        13148808097      NaN   NaN         NaN               NaN
        13205182768      NaN   NaN         NaN               NaN
        13302705766      NaN   NaN         NaN               NaN

                    post_office:brand:wikidata post_office:service_provider  \
element id
node    63253672                           NaN                          NaN
        285096511                          NaN                          NaN
        427670051                          NaN                          NaN
        427670057                          NaN                          NaN
        448594622                          NaN                          NaN
...                                        ...                          ...
        12793386255                        NaN                          NaN
        12829967540                        NaN                          NaN
        13148808097                        NaN                          NaN
        13205182768                        NaN                          NaN
        13302705766                        NaN                          NaN

                    name:signed toilets:wheelchair wheelchair:description  \
element id
node    63253672            NaN                NaN                    NaN
        285096511           NaN                NaN                    NaN
        427670051           NaN                NaN                    NaN
        427670057           NaN                NaN                    NaN
        448594622           NaN                NaN                    NaN
...                         ...                ...                    ...
        12793386255         NaN                NaN                    NaN
        12829967540         NaN                NaN                    NaN
        13148808097         NaN                NaN                    NaN
        13205182768         NaN                NaN                    NaN
        13302705766         NaN                NaN                    NaN

                    noname lottery post_office:ref origin alt_name cuisine  \
element id
node    63253672       NaN     NaN             NaN    NaN      NaN     NaN
        285096511      NaN     NaN             NaN    NaN      NaN     NaN
        427670051      NaN     NaN             NaN    NaN      NaN     NaN
        427670057      NaN     NaN             NaN    NaN      NaN     NaN
        448594622      NaN     NaN             NaN    NaN      NaN     NaN
...                    ...     ...             ...    ...      ...     ...
        12793386255    NaN     NaN             NaN    NaN      NaN     NaN
        12829967540    NaN     NaN             NaN    NaN      NaN     NaN
        13148808097    NaN     NaN             NaN    NaN      NaN     NaN
        13205182768    NaN     NaN             NaN    NaN      NaN     NaN
        13302705766    NaN     NaN             NaN    NaN      NaN     NaN

                    ref:vatin name:de name:en addr:floor air_conditioning  \
element id
node    63253672          NaN     NaN     NaN        NaN              NaN
        285096511         NaN     NaN     NaN        NaN              NaN
        427670051         NaN     NaN     NaN        NaN              NaN
        427670057         NaN     NaN     NaN        NaN              NaN
        448594622         NaN     NaN     NaN        NaN              NaN
...                       ...     ...     ...        ...              ...
        12793386255       NaN     NaN     NaN        NaN              NaN
        12829967540       NaN     NaN     NaN        NaN              NaN
        13148808097       NaN     NaN     NaN        NaN              NaN
        13205182768       NaN     NaN     NaN        NaN              NaN
        13302705766       NaN     NaN     NaN        NaN              NaN

                    contact:instagram contact:website internet_access  \
element id
node    63253672                  NaN             NaN             NaN
        285096511                 NaN             NaN             NaN
        427670051                 NaN             NaN             NaN
        427670057                 NaN             NaN             NaN
        448594622                 NaN             NaN             NaN
...                               ...             ...             ...
        12793386255               NaN             NaN             NaN
        12829967540               NaN             NaN             NaN
        13148808097               NaN             NaN             NaN
        13205182768               NaN             NaN             NaN
        13302705766               NaN             NaN             NaN

                    stroller toilets access:covid19 delivery:covid19  \
element id
node    63253672         NaN     NaN            NaN              NaN
        285096511        NaN     NaN            NaN              NaN
        427670051        NaN     NaN            NaN              NaN
        427670057        NaN     NaN            NaN              NaN
        448594622        NaN     NaN            NaN              NaN
...                      ...     ...            ...              ...
        12793386255      NaN     NaN            NaN              NaN
        12829967540      NaN     NaN            NaN              NaN
        13148808097      NaN     NaN            NaN              NaN
        13205182768      NaN     NaN            NaN              NaN
        13302705766      NaN     NaN            NaN              NaN

                    post_office:type contact:fax contact:phone name:ru  \
element id
node    63253672                 NaN         NaN           NaN     NaN
        285096511                NaN         NaN           NaN     NaN
        427670051                NaN         NaN           NaN     NaN
        427670057                NaN         NaN           NaN     NaN

In [107]:
# Convert non-point geometries (e.g., polygons) into representative points
spatis_gdf['geometry'] = spatis_gdf['geometry'].apply(
    lambda geom: geom if geom.geom_type == 'Point' else geom.representative_point()
)

# Extract latitude and longitude
spatis_gdf["latitude"] = spatis_gdf.geometry.y
spatis_gdf["longitude"] = spatis_gdf.geometry.x

# Display the updated GeoDataFrame
spatis_gdf

                                      geometry addr:city addr:country  \
element id
node    63253672     POINT (13.29612 52.49932)    Berlin           DE
        285096511    POINT (13.44904 52.51147)    Berlin           DE
        427670051    POINT (13.49642 52.51203)       NaN          NaN
        427670057    POINT (13.49707 52.51205)       NaN          NaN
        448594622     POINT (13.44111 52.5011)       NaN          NaN
...                                        ...       ...          ...
        12793386255  POINT (13.47928 52.50199)    Berlin          NaN
        12829967540  POINT (13.41345 52.54099)       NaN          NaN
        13148808097  POINT (13.47074 52.50639)       NaN          NaN
        13205182768  POINT (13.35372 52.49292)       NaN          NaN
        13302705766  POINT (13.38302 52.49293)       NaN          NaN

                    addr:housenumber addr:postcode               addr:street  \
element id
node    63253672                  39         10711  Joachim-Friedrich-Straße
        285096511                 43         10243            Gubener Straße
        427670051                NaN           NaN                       NaN
        427670057                243         10365         Frankfurter Allee
        448594622                NaN           NaN                       NaN
...                              ...           ...                       ...
        12793386255               17         10317             Nöldnerstraße
        12829967540                3           NaN           Danziger Straße
        13148808097              NaN           NaN                       NaN
        13205182768              NaN           NaN                       NaN
        13302705766              NaN           NaN                       NaN

                        addr:suburb amenity check_date:opening_hours  \
element id
node    63253672           Halensee     NaN                      NaN
        285096511    Friedrichshain     NaN                      NaN
        427670051               NaN     NaN                      NaN
        427670057               NaN     NaN                      NaN
        448594622               NaN     NaN               2024-03-29
...                             ...     ...                      ...
        12793386255             NaN     NaN                      NaN
        12829967540             NaN     NaN                      NaN
        13148808097             NaN     NaN                      NaN
        13205182768             NaN     NaN                      NaN
        13302705766             NaN     NaN                      NaN

                    compressed_air fuel:adblue fuel:biodiesel fuel:diesel  \
element id
node    63253672               NaN         NaN            NaN         NaN
        285096511              NaN         NaN            NaN         NaN
        427670051              NaN         NaN            NaN         NaN
        427670057              NaN         NaN            NaN         NaN
        448594622              NaN         NaN            NaN         NaN
...                            ...         ...            ...         ...
        12793386255            NaN         NaN            NaN         NaN
        12829967540            NaN         NaN            NaN         NaN
        13148808097            NaN         NaN            NaN         NaN
        13205182768            NaN         NaN            NaN         NaN
        13302705766            NaN         NaN            NaN         NaN

                    fuel:e10 fuel:octane_95 fuel:octane_98  \
element id
node    63253672         NaN            NaN            NaN
        285096511        NaN            NaN            NaN
        427670051        NaN            NaN            NaN
        427670057        NaN            NaN            NaN
        448594622        NaN            NaN            NaN
...                      ...            ...            ...
        12793386255      NaN            NaN            NaN
        12829967540      NaN            NaN            NaN
        13148808097      NaN            NaN            NaN
        13205182768      NaN            NaN            NaN
        13302705766      NaN            NaN            NaN

                                                   name  \
element id
node    63253672                              Späti Joe
        285096511                     Späti am Comenius
        427670051                                 Späti
        427670057       Sheran Späti + Hermes Paketshop
        448594622                      Späti am Schlesi
...                                                 ...
        12793386255  Confetti MiniMarket Spätkauf Späti
        12829967540                         Späti Gate1
        13148808097                               Späti
        13205182768                          Goltzspäti
        13302705766                     The Späti House

                                                         opening_hours  \
element id
node    63253672                                                  24/7
        285096511    Mo-Th 08:00-00:00, Fr 08:00-01:00, Sa 08:00-01...
        427670051                                 PH,Mo-Su 06:00-24:00
        427670057                                    Mo-Su 07:00-01:00
        448594622                                                  NaN
...                                                                ...
        12793386255                  Mo–Fr 11:00–21:00; So 12:00–21:00
        12829967540                                                NaN
        13148808097                                                NaN
        13205182768                                                NaN
        13302705766                                                NaN

                          operator         shop wheelchair brand  \
element id
node    63253672               NaN  convenience        NaN   NaN
        285096511    H.Y. Soysüren        kiosk    limited   NaN
        427670051              NaN  convenience        NaN   NaN
        427670057              NaN  convenience         no   NaN
        448594622              NaN  convenience         no   NaN
...                            ...          ...        ...   ...
        12793386255            NaN  convenience        NaN   NaN
        12829967540            NaN  convenience         no   NaN
        13148808097            NaN  convenience        NaN   NaN
        13205182768            NaN        kiosk        NaN   NaN
        13302705766            NaN  convenience         no   NaN

                    brand:wikidata brand:wikipedia fuel:GTL_diesel  \
element id
node    63253672               NaN             NaN             NaN
        285096511              NaN             NaN             NaN
        427670051              NaN             NaN             NaN
        427670057              NaN             NaN             NaN
        448594622              NaN             NaN             NaN
...                            ...             ...             ...
        12793386255            NaN             NaN             NaN
        12829967540            NaN             NaN             NaN
        13148808097            NaN             NaN             NaN
        13205182768            NaN             NaN             NaN
        13302705766            NaN             NaN             NaN

                    fuel:biogas fuel:cng fuel:lpg fuel:octane_102  \
element id
node    63253672            NaN      NaN      NaN             NaN
        285096511           NaN      NaN      NaN             NaN
        427670051           NaN      NaN      NaN             NaN
        427670057           NaN      NaN      NaN             NaN
        448594622           NaN      NaN      NaN             NaN
...                         ...      ...      ...             ...
        12793386255         NaN      NaN      NaN             NaN
        12829967540         NaN      NaN      NaN             NaN
        13148808097         NaN      NaN      NaN             NaN
        13205182768         NaN      NaN      NaN             NaN
        13302705766         NaN      NaN      NaN             NaN

                    surveillance website  check_date created_by  dog email  \
element id
node    63253672             NaN     NaN  2025-05-11        NaN  NaN   NaN
        285096511            NaN     NaN         NaN        NaN  NaN   NaN
        427670051            NaN     NaN         NaN        NaN  NaN   NaN
        427670057            NaN     NaN         NaN        NaN  NaN   NaN
        448594622            NaN     NaN  2024-12-23        NaN  NaN   NaN
...                          ...     ...         ...        ...  ...   ...
        12793386255          NaN     NaN         NaN        NaN  NaN   NaN
        12829967540          NaN     NaN  2025-05-10        NaN  NaN   NaN
        13148808097          NaN     NaN         NaN        NaN  NaN   NaN
        13205182768          NaN     NaN         NaN        NaN  NaN   NaN
        13302705766          NaN     NaN         NaN        NaN  NaN   NaN

                     fax          phone start_date indoor_seating organic  \
element id
node    63253672     NaN            NaN        NaN            NaN     NaN
        285096511    NaN            NaN        NaN            NaN     NaN
        427670051    NaN            NaN        NaN            NaN     NaN
        427670057    NaN            NaN        NaN            yes     NaN
        448594622    NaN            NaN        NaN            NaN     NaN
...                  ...            ...        ...            ...     ...
        12793386255  NaN  +493055631177        NaN            NaN     NaN
        12829967540  NaN            NaN        NaN            NaN     NaN
        13148808097  NaN            NaN        NaN            NaN     NaN
        13205182768  NaN            NaN        NaN            NaN     NaN
        13302705766  NaN            NaN        NaN            NaN     NaN

                    outdoor_seating smoking opening_hours:signed diet:halal  \
element id
node    63253672                NaN     NaN                  NaN        NaN
        285096511               NaN     NaN                  NaN        NaN
        427670051               NaN     NaN                  NaN        NaN
        427670057               yes     NaN                  NaN        NaN
        448594622          sidewalk     NaN                   no        NaN
...                             ...     ...                  ...        ...
        12793386255             NaN     NaN                  NaN        NaN
        12829967540             NaN     NaN                  NaN        NaN
        13148808097             NaN     NaN                  NaN        NaN
        13205182768             NaN     NaN                  NaN        NaN
        13302705766             NaN     NaN                  NaN        NaN

                    level payment:credit_cards payment:debit_cards  \
element id
node    63253672      NaN                  NaN                 NaN
        285096511     NaN                  NaN                 NaN
        427670051     NaN                  NaN                 NaN
        427670057     NaN                  NaN                 NaN
        448594622       0                  NaN                 NaN
...                   ...                  ...                 ...
        12793386255   NaN                  yes                 yes
        12829967540   NaN                  NaN                 NaN
        13148808097   NaN                  NaN                 NaN
        13205182768   NaN                  NaN                 NaN
        13302705766   NaN                  NaN                 NaN

                    payment:apple_pay payment:cards payment:cash  \
element id
node    63253672                  NaN           NaN          NaN
        285096511                 yes           yes          yes
        427670051                 NaN           NaN          NaN
        427670057                 NaN           NaN          NaN
        448594622                 NaN           NaN          NaN
...                               ...           ...          ...
        12793386255               NaN           NaN          NaN
        12829967540               NaN           NaN          NaN
        13148808097               NaN           NaN          NaN
        13205182768               NaN           NaN          NaN
        13302705766               NaN           NaN          NaN

                    payment:google_pay payment:paypal drink:club-mate  \
element id
node    63253672                   NaN            NaN             NaN
        285096511                  yes            yes             NaN
        427670051                  NaN            NaN             NaN
        427670057                  NaN            NaN             NaN
        448594622                  NaN            NaN             NaN
...                                ...            ...             ...
        12793386255                NaN            NaN             NaN
        12829967540                NaN            NaN             NaN
        13148808097                NaN            NaN             NaN
        13205182768                NaN            NaN             NaN
        13302705766                NaN            NaN             NaN

                    entrance craft post_office post_office:brand  \
element id
node    63253672         NaN   NaN         NaN               NaN
        285096511        NaN   NaN         NaN               NaN
        427670051        NaN   NaN         NaN               NaN
        427670057        NaN   NaN         NaN               NaN
        448594622        NaN   NaN         NaN               NaN
...                      ...   ...         ...               ...
        12793386255      NaN   NaN         NaN               NaN
        12829967540      NaN   NaN         NaN               NaN
        13148808097      NaN   NaN         NaN               NaN
        13205182768      NaN   NaN         NaN               NaN
        13302705766      NaN   NaN         NaN               NaN

                    post_office:brand:wikidata post_office:service_provider  \
element id
node    63253672                           NaN                          NaN
        285096511                          NaN                          NaN
        427670051                          NaN                          NaN
        427670057                          NaN                          NaN
        448594622                          NaN                          NaN
...                                        ...                          ...
        12793386255                        NaN                          NaN
        12829967540                        NaN                          NaN
        13148808097                        NaN                          NaN
        13205182768                        NaN                          NaN
        13302705766                        NaN                          NaN

                    name:signed toilets:wheelchair wheelchair:description  \
element id
node    63253672            NaN                NaN                    NaN
        285096511           NaN                NaN                    NaN
        427670051           NaN                NaN                    NaN
        427670057           NaN                NaN                    NaN
        448594622           NaN                NaN                    NaN
...                         ...                ...                    ...
        12793386255         NaN                NaN                    NaN
        12829967540         NaN                NaN                    NaN
        13148808097         NaN                NaN                    NaN
        13205182768         NaN                NaN                    NaN
        13302705766         NaN                NaN                    NaN

                    noname lottery post_office:ref origin alt_name cuisine  \
element id
node    63253672       NaN     NaN             NaN    NaN      NaN     NaN
        285096511      NaN     NaN             NaN    NaN      NaN     NaN
        427670051      NaN     NaN             NaN    NaN      NaN     NaN
        427670057      NaN     NaN             NaN    NaN      NaN     NaN
        448594622      NaN     NaN             NaN    NaN      NaN     NaN
...                    ...     ...             ...    ...      ...     ...
        12793386255    NaN     NaN             NaN    NaN      NaN     NaN
        12829967540    NaN     NaN             NaN    NaN      NaN     NaN
        13148808097    NaN     NaN             NaN    NaN      NaN     NaN
        13205182768    NaN     NaN             NaN    NaN      NaN     NaN
        13302705766    NaN     NaN             NaN    NaN      NaN     NaN

                    ref:vatin name:de name:en addr:floor air_conditioning  \
element id
node    63253672          NaN     NaN     NaN        NaN              NaN
        285096511         NaN     NaN     NaN        NaN              NaN
        427670051         NaN     NaN     NaN        NaN              NaN
        427670057         NaN     NaN     NaN        NaN              NaN
        448594622         NaN     NaN     NaN        NaN              NaN
...                       ...     ...     ...        ...              ...
        12793386255       NaN     NaN     NaN        NaN              NaN
        12829967540       NaN     NaN     NaN        NaN              NaN
        13148808097       NaN     NaN     NaN        NaN              NaN
        13205182768       NaN     NaN     NaN        NaN              NaN
        13302705766       NaN     NaN     NaN        NaN              NaN

                    contact:instagram contact:website internet_access  \
element id
node    63253672                  NaN             NaN             NaN
        285096511                 NaN             NaN             NaN
        427670051                 NaN             NaN             NaN
        427670057                 NaN             NaN             NaN
        448594622                 NaN             NaN             NaN
...                               ...             ...             ...
        12793386255               NaN             NaN             NaN
        12829967540               NaN             NaN             NaN
        13148808097               NaN             NaN             NaN
        13205182768               NaN             NaN             NaN
        13302705766               NaN             NaN             NaN

                    stroller toilets access:covid19 delivery:covid19  \
element id
node    63253672         NaN     NaN            NaN              NaN
        285096511        NaN     NaN            NaN              NaN
        427670051        NaN     NaN            NaN              NaN
        427670057        NaN     NaN            NaN              NaN
        448594622        NaN     NaN            NaN              NaN
...                      ...     ...            ...              ...
        12793386255      NaN     NaN            NaN              NaN
        12829967540      NaN     NaN            NaN              NaN
        13148808097      NaN     NaN            NaN              NaN
        13205182768      NaN     NaN            NaN              NaN
        13302705766      NaN     NaN            NaN              NaN

                    post_office:type contact:fax contact:phone name:ru  \
element id
node    63253672                 NaN         NaN           NaN     NaN
        285096511                NaN         NaN           NaN     NaN
        427670051                NaN         NaN           NaN     NaN
        427670057                NaN         NaN           NaN     NaN

In [91]:
# Select the 25 columns (fill missing with None if not present)

selected_columns = [
    #"osmid",
    "name", "brand", "operator",
    "addr:street", "addr:housenumber", "addr:postcode", "addr:suburb","addr:city", "addr:country",
    "phone", "email", "website", "opening_hours",
    "payment:visa", "payment:mastercard","payment:girocard", "dispensing", "delivery","surveillance","wheelchair", "building",
    "latitude", "longitude", "geometry",
    # placeholders for enrichment
    #"neighbourhood", "district",
    # add source info
    "source"
]  # Added the closing bracket here

In [92]:
# Rename map for only the columns that need renaming

rename_map = {
    "addr:street": "street",
    "addr:housenumber": "housenumber",
    "addr:postcode": "postcode",
    "addr:suburb": "suburb",
    "addr:city": "city",
    "addr:country": "country",
    "payment:visa": "payment_visa",
    "payment:mastercard": "payment_mastercard",
    "payment:girocard": "payment_girocard",
    "opening_hours": "openinghours",
    "wheelchair": "wheelchair_accessible",
    "building": "building_type"
}

In [93]:
# First, check what columns are actually available in the DataFrame
print(spatis_gdf.columns)

# Then select only the columns that exist
# Option 1: Remove 'dispensing' from your selected_columns list
selected_columns = [col for col in selected_columns if col != 'dispensing']
spatis_gd = spatis_gdf[selected_columns]

# Option 2: If you need 'dispensing' but it might have a different name
# Check if a similar column exists and use that instead
# For example, it might be called 'dispense' or 'dispensary' instead
# spatis_gd = spatis_gdf[corrected_column_list]

Index(['geometry', 'addr:city', 'addr:country', 'addr:housenumber',
       'addr:postcode', 'addr:street', 'addr:suburb', 'amenity',
       'check_date:opening_hours', 'compressed_air',
       ...
       'facebook', 'access', 'indoor', 'room', 'height', 'building:part',
       'name:ja', 'biergarten', 'latitude', 'longitude'],
      dtype='object', length=263)

In [94]:
# Preview the final DataFrame
spatis_gdf.head()

                                    geometry addr:city addr:country  \
element id
node    63253672   POINT (13.29612 52.49932)    Berlin           DE
        285096511  POINT (13.44904 52.51147)    Berlin           DE
        427670051  POINT (13.49642 52.51203)       NaN          NaN
        427670057  POINT (13.49707 52.51205)       NaN          NaN
        448594622   POINT (13.44111 52.5011)       NaN          NaN

                  addr:housenumber addr:postcode               addr:street  \
element id
node    63253672                39         10711  Joachim-Friedrich-Straße
        285096511               43         10243            Gubener Straße
        427670051              NaN           NaN                       NaN
        427670057              243         10365         Frankfurter Allee
        448594622              NaN           NaN                       NaN

                      addr:suburb amenity check_date:opening_hours  \
element id
node    63253672         Halensee     NaN                      NaN
        285096511  Friedrichshain     NaN                      NaN
        427670051             NaN     NaN                      NaN
        427670057             NaN     NaN                      NaN
        448594622             NaN     NaN               2024-03-29

                  compressed_air fuel:adblue fuel:biodiesel fuel:diesel  \
element id
node    63253672             NaN         NaN            NaN         NaN
        285096511            NaN         NaN            NaN         NaN
        427670051            NaN         NaN            NaN         NaN
        427670057            NaN         NaN            NaN         NaN
        448594622            NaN         NaN            NaN         NaN

                  fuel:e10 fuel:octane_95 fuel:octane_98  \
element id
node    63253672       NaN            NaN            NaN
        285096511      NaN            NaN            NaN
        427670051      NaN            NaN            NaN
        427670057      NaN            NaN            NaN
        448594622      NaN            NaN            NaN

                                              name  \
element id
node    63253672                         Späti Joe
        285096511                Späti am Comenius
        427670051                            Späti
        427670057  Sheran Späti + Hermes Paketshop
        448594622                 Späti am Schlesi

                                                       opening_hours  \
element id
node    63253672                                                24/7
        285096511  Mo-Th 08:00-00:00, Fr 08:00-01:00, Sa 08:00-01...
        427670051                               PH,Mo-Su 06:00-24:00
        427670057                                  Mo-Su 07:00-01:00
        448594622                                                NaN

                        operator         shop wheelchair brand brand:wikidata  \
element id
node    63253672             NaN  convenience        NaN   NaN            NaN
        285096511  H.Y. Soysüren        kiosk    limited   NaN            NaN
        427670051            NaN  convenience        NaN   NaN            NaN
        427670057            NaN  convenience         no   NaN            NaN
        448594622            NaN  convenience         no   NaN            NaN

                  brand:wikipedia fuel:GTL_diesel fuel:biogas fuel:cng  \
element id
node    63253672              NaN             NaN         NaN      NaN
        285096511             NaN             NaN         NaN      NaN
        427670051             NaN             NaN         NaN      NaN
        427670057             NaN             NaN         NaN      NaN
        448594622             NaN             NaN         NaN      NaN

                  fuel:lpg fuel:octane_102 surveillance website  check_date  \
element id
node    63253672       NaN             NaN          NaN     NaN  2025-05-11
        285096511      NaN             NaN          NaN     NaN         NaN
        427670051      NaN             NaN          NaN     NaN         NaN
        427670057      NaN             NaN          NaN     NaN         NaN
        448594622      NaN             NaN          NaN     NaN  2024-12-23

                  created_by  dog email  fax phone start_date indoor_seating  \
element id
node    63253672         NaN  NaN   NaN  NaN   NaN        NaN            NaN
        285096511        NaN  NaN   NaN  NaN   NaN        NaN            NaN
        427670051        NaN  NaN   NaN  NaN   NaN        NaN            NaN
        427670057        NaN  NaN   NaN  NaN   NaN        NaN            yes
        448594622        NaN  NaN   NaN  NaN   NaN        NaN            NaN

                  organic outdoor_seating smoking opening_hours:signed  \
element id
node    63253672      NaN             NaN     NaN                  NaN
        285096511     NaN             NaN     NaN                  NaN
        427670051     NaN             NaN     NaN                  NaN
        427670057     NaN             yes     NaN                  NaN
        448594622     NaN        sidewalk     NaN                   no

                  diet:halal level payment:credit_cards payment:debit_cards  \
element id
node    63253672         NaN   NaN                  NaN                 NaN
        285096511        NaN   NaN                  NaN                 NaN
        427670051        NaN   NaN                  NaN                 NaN
        427670057        NaN   NaN                  NaN                 NaN
        448594622        NaN     0                  NaN                 NaN

                  payment:apple_pay payment:cards payment:cash  \
element id
node    63253672                NaN           NaN          NaN
        285096511               yes           yes          yes
        427670051               NaN           NaN          NaN
        427670057               NaN           NaN          NaN
        448594622               NaN           NaN          NaN

                  payment:google_pay payment:paypal drink:club-mate entrance  \
element id
node    63253672                 NaN            NaN             NaN      NaN
        285096511                yes            yes             NaN      NaN
        427670051                NaN            NaN             NaN      NaN
        427670057                NaN            NaN             NaN      NaN
        448594622                NaN            NaN             NaN      NaN

                  craft post_office post_office:brand  \
element id
node    63253672    NaN         NaN               NaN
        285096511   NaN         NaN               NaN
        427670051   NaN         NaN               NaN
        427670057   NaN         NaN               NaN
        448594622   NaN         NaN               NaN

                  post_office:brand:wikidata post_office:service_provider  \
element id
node    63253672                         NaN                          NaN
        285096511                        NaN                          NaN
        427670051                        NaN                          NaN
        427670057                        NaN                          NaN
        448594622                        NaN                          NaN

                  name:signed toilets:wheelchair wheelchair:description  \
element id
node    63253672          NaN                NaN                    NaN
        285096511         NaN                NaN                    NaN
        427670051         NaN                NaN                    NaN
        427670057         NaN                NaN                    NaN
        448594622         NaN                NaN                    NaN

                  noname lottery post_office:ref origin alt_name cuisine  \
element id
node    63253672     NaN     NaN             NaN    NaN      NaN     NaN
        285096511    NaN     NaN             NaN    NaN      NaN     NaN
        427670051    NaN     NaN             NaN    NaN      NaN     NaN
        427670057    NaN     NaN             NaN    NaN      NaN     NaN
        448594622    NaN     NaN             NaN    NaN      NaN     NaN

                  ref:vatin name:de name:en addr:floor air_conditioning  \
element id
node    63253672        NaN     NaN     NaN        NaN              NaN
        285096511       NaN     NaN     NaN        NaN              NaN
        427670051       NaN     NaN     NaN        NaN              NaN
        427670057       NaN     NaN     NaN        NaN              NaN
        448594622       NaN     NaN     NaN        NaN              NaN

                  contact:instagram contact:website internet_access stroller  \
element id
node    63253672                NaN             NaN             NaN      NaN
        285096511               NaN             NaN             NaN      NaN
        427670051               NaN             NaN             NaN      NaN
        427670057               NaN             NaN             NaN      NaN
        448594622               NaN             NaN             NaN      NaN

                  toilets access:covid19 delivery:covid19 post_office:type  \
element id
node    63253672      NaN            NaN              NaN              NaN
        285096511     NaN            NaN              NaN              NaN
        427670051     NaN            NaN              NaN              NaN
        427670057     NaN            NaN              NaN              NaN
        448594622     NaN            NaN              NaN              NaN

                  contact:fax contact:phone name:ru opening_hours:covid19  \
element id
node    63253672          NaN           NaN     NaN                   NaN
        285096511         NaN           NaN     NaN                   NaN
        427670051         NaN           NaN     NaN                   NaN
        427670057         NaN           NaN     NaN                   NaN
        448594622         NaN           NaN     NaN                   NaN

                  takeaway:covid19 internet_access:fee  atm atm:operator  \
element id
node    63253672               NaN                 NaN  NaN          NaN
        285096511              NaN                 NaN  NaN          NaN
        427670051              NaN                 NaN  NaN          NaN
        427670057              NaN                 NaN  NaN          NaN
        448594622              NaN                 NaN  NaN          NaN

                  note:de ref:Hermes description coffee tobacco note  \
element id
node    63253672      NaN        NaN         NaN    NaN     NaN  NaN
        285096511     NaN        NaN         NaN    NaN     NaN  NaN
        427670051     NaN        NaN         NaN    NaN     NaN  NaN
        427670057     NaN        NaN         NaN    NaN     NaN  NaN
        448594622     NaN        NaN         NaN    NaN     NaN  NaN

                  operator:wikidata  ref currency:EUR source diet:gluten_free  \
element id
node    63253672                NaN  NaN          NaN    NaN              NaN
        285096511               NaN  NaN          NaN    NaN              NaN
        427670051               NaN  NaN          NaN    NaN              NaN
        427670057               NaN  NaN          NaN    NaN              NaN
        448594622               NaN  NaN          NaN    NaN              NaN

                  leisure cafe payment:coins vending:sweets vending:toys  \
element id
node    63253672      NaN  NaN           NaN            NaN          NaN
        285096511     NaN  NaN           NaN            NaN          NaN
        427670051     NaN  NaN           NaN            NaN          NaN
        427670057     NaN  NaN           NaN            NaN          NaN
        448594622     NaN  NaN           NaN            NaN          NaN

                  service:phone type diet:kosher diet:vegetarian post_box  \
element id
node    63253672            NaN  NaN         NaN             NaN      NaN
        285096511           NaN  NaN         NaN             NaN      NaN
        427670051           NaN  NaN         NaN             NaN      NaN
        427670057           NaN  NaN         NaN             NaN      NaN
        448594622           NaN  NaN         NaN             NaN      NaN

                  operator:wikipedia changing_table payment:mastercard  \
element id
node    63253672                 NaN            NaN                NaN
        285096511                NaN            NaN                NaN
        427670051                NaN            NaN                NaN
        427670057                NaN            NaN                NaN
        448594622                NaN            NaN                NaN

                  payment:visa second_hand toilets:menstrual_products  \
element id
node    63253672           NaN         NaN                        NaN
        285096511          NaN         NaN                        NaN
        427670051          NaN         NaN                        NaN
        427670057          NaN         NaN                        NaN
        448594622          NaN         NaN                        NaN

                  takeaway toilets:access parcel_pickup drink:coffee  \
element id
node    63253672       NaN            NaN           NaN          NaN
        285096511      NaN            NaN           NaN          NaN
        427670051      NaN            NaN           NaN          NaN
        427670057      NaN            NaN           NaN          NaN
        448594622      NaN            NaN           NaN          NaN

                  sells:tobacco name:zh addr:housename fixme  \
element id
node    63253672            NaN     NaN            NaN   NaN
        285096511           NaN     NaN            NaN   NaN
        427670051           NaN     NaN            NaN   NaN
        427670057           NaN     NaN            NaN   NaN
        448594622           NaN     NaN            NaN   NaN

                  description:payment payment:cards:min_payment  \
element id
node    63253672                  NaN                       NaN
        285096511                 NaN                       NaN
        427670051                 NaN                       NaN
        427670057                 NaN                       NaN
        448594622                 NaN                       NaN

                  post_office:parcel_from post_office:parcel_to  \
element id
node    63253672                      NaN                   NaN
        285096511                     NaN                   NaN
        427670051                     NaN                   NaN
        427670057                     NaN                   NaN
        448594622                     NaN                   NaN

                  contact:mobile dry_cleaning ice_cream drink:beer  \
element id
node    63253672             NaN          NaN       NaN        NaN
        285096511            NaN          NaN       NaN        NaN
        427670051            NaN          NaN       NaN        NaN
        427670057            NaN          NaN       NaN        NaN
        448594622            NaN          NaN       NaN        NaN

                  tickets:public_transport diet:vegan branch bulk_purchase  \
element id
node    63253672                       NaN        NaN    NaN           NaN
        285096511                      NaN        NaN    NaN           NaN
        427670051                      NaN        NaN    NaN           NaN
        427670057                      NaN        NaN    NaN           NaN
        448594622                      NaN        NaN    NaN           NaN

                  diet:organic frozen_yogurt reusable_packaging:offer  \
element id
node    63253672           NaN           NaN                      NaN
        285096511          NaN           NaN                      NaN
        427670051          NaN           NaN                      NaN
        427670057          NaN           NaN                      NaN
        448594622          NaN           NaN                      NaN

                  contact:email lgbtq post_office:letter fuel:HGV_diesel  \
element id
node    63253672            NaN   NaN                NaN             NaN
        285096511           NaN   NaN                NaN             NaN
        427670051           NaN   NaN                NaN             NaN
        427670057           NaN   NaN                NaN             NaN
        448594622           NaN   NaN                NaN             NaN

                  fuel:octane_100 addr:place post_office:parcel_pickup  \
element id
node    63253672              NaN        NaN                       NaN
        285096511             NaN        NaN                       NaN
        427670051             NaN        NaN                       NaN
        427670057             NaN        NaN                       NaN
        448594622             NaN        NaN                       NaN

                  ref:deutsche_post tourism fair_trade payment:contactless  \
element id
node    63253672                NaN     NaN        NaN                 NaN
        285096511               NaN     NaN        NaN                 NaN
        427670051               NaN     NaN        NaN                 NaN
        427670057               NaN     NaN        NaN                 NaN
        448594622               NaN     NaN        NaN                 NaN

                  payment:maestro payment:v_pay payment:app mapillary  \
element id
node    63253672              NaN           NaN         NaN       NaN
        285096511             NaN           NaN         NaN       NaN
        427670051             NaN           NaN         NaN       NaN
        427670057             NaN           NaN         NaN       NaN
        448594622             NaN           NaN         NaN       NaN

                  opening_date post_office:operator payment:others cash_in  \
element id
node    63253672           NaN                  NaN            NaN     NaN
        285096511          NaN                  NaN            NaN     NaN
        427670051          NaN                  NaN            NaN     NaN
        427670057          NaN                  NaN            NaN     NaN
        448594622          NaN                  NaN            NaN     NaN

                  survey:date post_office:letter_from post_office:packaging  \
element id
node    63253672          NaN                     NaN                   NaN
        285096511         NaN                     NaN                   NaN
        427670051         NaN                     NaN                   NaN
        427670057         NaN                     NaN                   NaN
        448594622         NaN                     NaN                   NaN

                  post_office:stamps payment:girocard description:en old_name  \
element id
node    63253672                 NaN              NaN            NaN      NaN
        285096511                NaN              NaN            NaN      NaN
        427670051                NaN              NaN            NaN      NaN
        427670057                NaN              NaN            NaN      NaN
        448594622                NaN              NaN            NaN      NaN

                  car_repair car_wash old_addr:housenumber old_addr:street  \
element id
node    63253672         NaN      NaN                  NaN             NaN
        285096511        NaN      NaN                  NaN             NaN
        427670051        NaN      NaN                  NaN             NaN
        427670057        NaN      NaN                  NaN             NaN
        448594622        NaN      NaN                  NaN             NaN

                  contact:facebook reusable_packaging:accept wikidata  \
element id
node    63253672               NaN                       NaN      NaN

In [95]:
# Data types and non-null counts

spatis_gdf.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
MultiIndex: 151 entries, ('node', np.int64(63253672)) to ('node', np.int64(13302705766))
Columns: 263 entries, geometry to longitude
dtypes: float64(2), geometry(1), object(260)
memory usage: 389.0+ KB

In [96]:
import osmnx as ox
import geopandas as gpd

districts_gdf = ox.features_from_place(
    "Berlin, Germany",
    {"boundary": "administrative", "admin_level": "9"}
)

districts_gdf.head()

                                                         geometry  \
element  id
relation 16328  POLYGON ((13.30038 52.56998, 13.3019 52.57144,...
         16330  POLYGON ((13.26423 52.62686, 13.26438 52.62802...
         16334  POLYGON ((13.2082 52.59899, 13.20724 52.59987,...
         16343  POLYGON ((13.10932 52.45071, 13.10956 52.45108...
         16346  POLYGON ((13.27034 52.54934, 13.27061 52.54934...

                      boundary                 name  ref admin_level name:ab  \
element  id
relation 16328  administrative        Reinickendorf  NaN          10     NaN
         16330  administrative              Frohnau  NaN          10     NaN
         16334  administrative        Reinickendorf  NaN           9     NaN
         16343  administrative              Spandau  NaN           9     NaN
         16346  administrative  Charlottenburg-Nord  NaN          10     NaN

               name:af name:als name:am name:an name:ang name:ar name:arc  \
element  id
relation 16328     NaN      NaN     NaN     NaN      NaN     NaN      NaN
         16330     NaN      NaN     NaN     NaN      NaN     NaN      NaN
         16334     NaN      NaN     NaN     NaN      NaN     NaN      NaN
         16343     NaN      NaN     NaN     NaN      NaN     NaN      NaN
         16346     NaN      NaN     NaN     NaN      NaN     NaN      NaN

               name:arz name:ast name:av name:az name:ba name:bar  \
element  id
relation 16328      NaN      NaN     NaN     NaN     NaN      NaN
         16330      NaN      NaN     NaN     NaN     NaN      NaN
         16334      NaN      NaN     NaN     NaN     NaN      NaN
         16343      NaN      NaN     NaN     NaN     NaN      NaN
         16346      NaN      NaN     NaN     NaN     NaN      NaN

               name:bat-smg name:be name:be-tarask name:bg name:bi name:bn  \
element  id
relation 16328          NaN     NaN            NaN     NaN     NaN     NaN
         16330          NaN     NaN            NaN     NaN     NaN     NaN
         16334          NaN     NaN            NaN     NaN     NaN     NaN
         16343          NaN     NaN            NaN     NaN     NaN     NaN
         16346          NaN     NaN            NaN     NaN     NaN     NaN

               name:bo name:br name:bs name:bxr name:ca name:cbk-zam name:ce  \
element  id
relation 16328     NaN     NaN     NaN      NaN     NaN          NaN     NaN
         16330     NaN     NaN     NaN      NaN     NaN          NaN     NaN
         16334     NaN     NaN     NaN      NaN     NaN          NaN     NaN
         16343     NaN     NaN     NaN      NaN     NaN          NaN     NaN
         16346     NaN     NaN     NaN      NaN     NaN          NaN     NaN

               name:ckb name:co name:crh name:cs name:csb name:cu name:cv  \
element  id
relation 16328      NaN     NaN      NaN     NaN      NaN     NaN     NaN
         16330      NaN     NaN      NaN     NaN      NaN     NaN     NaN
         16334      NaN     NaN      NaN     NaN      NaN     NaN     NaN
         16343      NaN     NaN      NaN     NaN      NaN     NaN     NaN
         16346      NaN     NaN      NaN     NaN      NaN     NaN     NaN

               name:cy name:da        name:de name:diq name:dsb name:el  \
element  id
relation 16328     NaN     NaN  Reinickendorf      NaN      NaN     NaN
         16330     NaN     NaN            NaN      NaN      NaN     NaN
         16334     NaN     NaN            NaN      NaN      NaN     NaN
         16343     NaN     NaN            NaN      NaN      NaN     NaN
         16346     NaN     NaN            NaN      NaN      NaN     NaN

               name:en name:eo name:es name:et name:eu name:ext name:fa  \
element  id
relation 16328     NaN     NaN     NaN     NaN     NaN      NaN     NaN
         16330     NaN     NaN     NaN     NaN     NaN      NaN     NaN
         16334     NaN     NaN     NaN     NaN     NaN      NaN     NaN
         16343     NaN     NaN     NaN     NaN     NaN      NaN     NaN
         16346     NaN     NaN     NaN     NaN     NaN      NaN     NaN

               name:fi name:fo name:fr name:frp name:fur name:fy name:ga  \
element  id
relation 16328     NaN     NaN     NaN      NaN      NaN     NaN     NaN
         16330     NaN     NaN     NaN      NaN      NaN     NaN     NaN
         16334     NaN     NaN     NaN      NaN      NaN     NaN     NaN
         16343     NaN     NaN     NaN      NaN      NaN     NaN     NaN
         16346     NaN     NaN     NaN      NaN      NaN     NaN     NaN

               name:gan name:gd name:gl name:gn name:gu name:gv name:haw  \
element  id
relation 16328      NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16330      NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16334      NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16343      NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16346      NaN     NaN     NaN     NaN     NaN     NaN      NaN

                    name:he name:hi name:hr name:hsb name:ht name:hu name:hy  \
element  id
relation 16328          NaN     NaN     NaN      NaN     NaN     NaN     NaN
         16330          NaN     NaN     NaN      NaN     NaN     NaN     NaN
         16334  רייניקנדורף     NaN     NaN      NaN     NaN     NaN     NaN
         16343          NaN     NaN     NaN      NaN     NaN     NaN     NaN
         16346          NaN     NaN     NaN      NaN     NaN     NaN     NaN

               name:ia name:id name:ie name:ilo name:io name:is name:it  \
element  id
relation 16328     NaN     NaN     NaN      NaN     NaN     NaN     NaN
         16330     NaN     NaN     NaN      NaN     NaN     NaN     NaN
         16334     NaN     NaN     NaN      NaN     NaN     NaN     NaN
         16343     NaN     NaN     NaN      NaN     NaN     NaN     NaN
         16346     NaN     NaN     NaN      NaN     NaN     NaN     NaN

               name:iu name:ja name:jbo name:jv name:ka name:kab name:kbd  \
element  id
relation 16328     NaN     NaN      NaN     NaN     NaN      NaN      NaN
         16330     NaN     NaN      NaN     NaN     NaN      NaN      NaN
         16334     NaN     NaN      NaN     NaN     NaN      NaN      NaN
         16343     NaN     NaN      NaN     NaN     NaN      NaN      NaN
         16346     NaN     NaN      NaN     NaN     NaN      NaN      NaN

               name:kk name:km name:kn name:ko name:koi name:ks name:ksh  \
element  id
relation 16328     NaN     NaN     NaN     NaN      NaN     NaN      NaN
         16330     NaN     NaN     NaN     NaN      NaN     NaN      NaN
         16334     NaN     NaN     NaN     NaN      NaN     NaN      NaN
         16343     NaN     NaN     NaN     NaN      NaN     NaN      NaN
         16346     NaN     NaN     NaN     NaN      NaN     NaN      NaN

               name:ku name:kv name:kw name:ky name:la name:lb name:lez  \
element  id
relation 16328     NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16330     NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16334     NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16343     NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16346     NaN     NaN     NaN     NaN     NaN     NaN      NaN

               name:lg name:li name:lij name:lmo name:ln name:lo name:lt  \
element  id
relation 16328     NaN     NaN      NaN      NaN     NaN     NaN     NaN
         16330     NaN     NaN      NaN      NaN     NaN     NaN     NaN
         16334     NaN     NaN      NaN      NaN     NaN     NaN     NaN
         16343     NaN     NaN      NaN      NaN     NaN     NaN     NaN
         16346     NaN     NaN      NaN      NaN     NaN     NaN     NaN

               name:ltg name:lv name:lzh name:mg name:mhr name:mi name:mk  \
element  id
relation 16328      NaN     NaN      NaN     NaN      NaN     NaN     NaN
         16330      NaN     NaN      NaN     NaN      NaN     NaN     NaN
         16334      NaN     NaN      NaN     NaN      NaN     NaN     NaN
         16343      NaN     NaN      NaN     NaN      NaN     NaN     NaN
         16346      NaN     NaN      NaN     NaN      NaN     NaN     NaN

               name:ml name:mn name:mr name:ms name:mt name:my name:myv  \
element  id
relation 16328     NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16330     NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16334     NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16343     NaN     NaN     NaN     NaN     NaN     NaN      NaN
         16346     NaN     NaN     NaN     NaN     NaN     NaN      NaN

               name:mzn name:na name:nah name:nan name:nap name:nds  \
element  id
relation 16328      NaN     NaN      NaN      NaN      NaN      NaN
         16330      NaN     NaN      NaN      NaN      NaN      NaN
         16334      NaN     NaN      NaN      NaN      NaN      NaN
         16343      NaN     NaN      NaN      NaN      NaN      NaN
         16346      NaN     NaN      NaN      NaN      NaN      NaN

               name:nds-nl name:ne name:nl name:nn name:no name:nov name:nrm  \
element  id
relation 16328         NaN     NaN     NaN     NaN     NaN      NaN      NaN
         16330         NaN     NaN     NaN     NaN     NaN      NaN      NaN
         16334         NaN     NaN     NaN     NaN     NaN      NaN      NaN
         16343         NaN     NaN     NaN     NaN     NaN      NaN      NaN
         16346         NaN     NaN     NaN     NaN     NaN      NaN      NaN

               name:nv name:oc name:os name:pa name:pam name:pdc name:pfl  \
element  id
relation 16328     NaN     NaN     NaN     NaN      NaN      NaN      NaN
         16330     NaN     NaN     NaN     NaN      NaN      NaN      NaN
         16334     NaN     NaN     NaN     NaN      NaN      NaN      NaN
         16343     NaN     NaN     NaN     NaN      NaN      NaN      NaN
         16346     NaN     NaN     NaN     NaN      NaN      NaN      NaN

               name:pl name:pms name:pnb name:pnt name:prefix name:ps name:pt  \
element  id
relation 16328     NaN      NaN      NaN      NaN    Ortsteil     NaN     NaN
         16330     NaN      NaN      NaN      NaN    Ortsteil     NaN     NaN
         16334     NaN      NaN      NaN      NaN      Bezirk     NaN     NaN
         16343     NaN      NaN      NaN      NaN      Bezirk     NaN     NaN
         16346     NaN      NaN      NaN      NaN    Ortsteil     NaN     NaN

               name:qu name:rm name:rmy name:ro name:roa-rup name:roa-tara  \
element  id
relation 16328     NaN     NaN      NaN     NaN          NaN           NaN
         16330     NaN     NaN      NaN     NaN          NaN           NaN
         16334     NaN     NaN      NaN     NaN          NaN           NaN
         16343     NaN     NaN      NaN     NaN          NaN           NaN
         16346     NaN     NaN      NaN     NaN          NaN           NaN

                           name:ru name:rue name:sa name:sah name:sc name:scn  \
element  id
relation 16328       Райниккендорф      NaN     NaN      NaN     NaN      NaN
         16330              Фронау      NaN     NaN      NaN     NaN      NaN
         16334       Райниккендорф      NaN     NaN      NaN     NaN      NaN
         16343             Шпандау      NaN     NaN      NaN     NaN      NaN
         16346  Шарлоттенбург-Норд      NaN     NaN      NaN     NaN      NaN

               name:sco name:se name:sh name:short name:si name:sk name:sl  \
element  id
relation 16328      NaN     NaN     NaN        NaN     NaN     NaN     NaN
         16330      NaN     NaN     NaN        NaN     NaN     NaN     NaN
         16334      NaN     NaN     NaN        NaN     NaN     NaN     NaN
         16343      NaN     NaN     NaN        NaN     NaN     NaN     NaN
         16346      NaN     NaN     NaN        NaN     NaN     NaN     NaN

               name:sm name:so name:sq name:sr name:stq name:su name:sv  \
element  id
relation 16328     NaN     NaN     NaN     NaN      NaN     NaN     NaN
         16330     NaN     NaN     NaN     NaN      NaN     NaN     NaN
         16334     NaN     NaN     NaN     NaN      NaN     NaN     NaN
         16343     NaN     NaN     NaN     NaN      NaN     NaN     NaN
         16346     NaN     NaN     NaN     NaN      NaN     NaN     NaN

               name:sw name:szl name:ta name:te name:tet name:tg name:th  \
element  id
relation 16328     NaN      NaN     NaN     NaN      NaN     NaN     NaN
         16330     NaN      NaN     NaN     NaN      NaN     NaN     NaN
         16334     NaN      NaN     NaN     NaN      NaN     NaN     NaN
         16343     NaN      NaN     NaN     NaN      NaN     NaN     NaN
         16346     NaN      NaN     NaN     NaN      NaN     NaN     NaN

               name:ti name:tl name:tpi name:tr name:tt name:tw name:ty  \
element  id
relation 16328     NaN     NaN      NaN     NaN     NaN     NaN     NaN
         16330     NaN     NaN      NaN     NaN     NaN     NaN     NaN
         16334     NaN     NaN      NaN     NaN     NaN     NaN     NaN
         16343     NaN     NaN      NaN     NaN     NaN     NaN     NaN
         16346     NaN     NaN      NaN     NaN     NaN     NaN     NaN

               name:tzl name:udm name:ug       name:uk name:ur name:uz  \
element  id
relation 16328      NaN      NaN     NaN           NaN     NaN     NaN
         16330      NaN      NaN     NaN           NaN     NaN     NaN
         16334      NaN      NaN     NaN  Райнікендорф     NaN     NaN
         16343      NaN      NaN     NaN           NaN     NaN     NaN
         16346      NaN      NaN     NaN           NaN     NaN     NaN

               name:vec name:vi name:vls name:vro name:wo name:xh name:xmf  \
element  id
relation 16328      NaN     NaN      NaN      NaN     NaN     NaN      NaN
         16330      NaN     NaN      NaN      NaN     NaN     NaN      NaN
         16334      NaN     NaN      NaN      NaN     NaN     NaN      NaN
         16343      NaN     NaN      NaN      NaN     NaN     NaN      NaN
         16346      NaN     NaN      NaN      NaN     NaN     NaN      NaN

               name:yi name:yo name:yue name:zea name:zh name:zh-Hans  \
element  id
relation 16328     NaN     NaN      NaN      NaN     NaN          NaN
         16330     NaN     NaN      NaN      NaN     NaN          NaN
         16334     NaN     NaN      NaN      NaN     NaN          NaN
         16343     NaN     NaN      NaN      NaN     NaN          NaN
         16346     NaN     NaN      NaN      NaN     NaN          NaN

               name:zh-Hant name:zu official_status official_status:de  \
element  id
relation 16328          NaN     NaN             NaN                NaN
         16330          NaN     NaN             NaN                NaN
         16334          NaN     NaN             NaN                NaN
         16343          NaN     NaN             NaN                NaN
         16346          NaN     NaN             NaN                NaN

               official_status:en official_status:ru old_name:vi place  \
element  id
relation 16328                NaN                NaN         NaN   NaN
         16330                NaN                NaN         NaN   NaN
         16334                NaN                NaN         NaN   NaN
         16343                NaN                NaN         NaN   NaN
         16346                NaN                NaN         NaN   NaN

               population                                 website wikidata  \
element  id
relation 16328        NaN                                     NaN  Q694034
         16330        NaN                                     NaN  Q641467
         16334     266123  http://www.berlin.de/ba-reinickendorf/  Q158876
         16343     245527        http://www.berlin.de/ba-spandau/  Q158083
         16346        NaN                                     NaN  Q659451

                                    wikipedia  \
element  id
relation 16328        de:Berlin-Reinickendorf
         16330              de:Berlin-Frohnau
         16334        de:Bezirk Reinickendorf
         16343              de:Bezirk Spandau
         16346  de:Berlin-Charlottenburg-Nord

                                     description  \
element  id
relation 16328                               NaN
         16330                               NaN
         16334  12. Verwaltungsbezirk von Berlin
         16343   5. Verwaltungsbezirk von Berlin
         16346                               NaN

                                                           source  \
element  id
relation 16328  http://wiki.openstreetmap.org/wiki/Import/Cata...
         16330  http://wiki.openstreetmap.org/wiki/Import/Cata...
         16334  http://wiki.openstreetmap.org/wiki/Import/Cata...
         16343  http://wiki.openstreetmap.org/wiki/Import/Cata...
         16346  http://wiki.openstreetmap.org/wiki/Import/Cata...

               TMC:cid_58:tabcd_1:Class TMC:cid_58:tabcd_1:LCLversion  \
element  id
relation 16328                      NaN                           NaN
         16330                     Area                          9.00
         16334                     Area                          9.00
         16343                      NaN                           NaN
         16346                      NaN                           NaN

               TMC:cid_58:tabcd_1:LocationCode image note  \
element  id
relation 16328                             NaN   NaN  NaN
         16330                           32549   NaN  NaN
         16334                            4942   NaN  NaN
         16343                             NaN   NaN  NaN
         16346                             NaN   NaN  NaN

                           alt_name long_name border_type name:gsw old_name  \
element  id
relation 16328                  NaN       NaN         NaN      NaN      NaN
         16330  Gartenstadt Frohnau       NaN         NaN      NaN      NaN
         16334                  NaN       NaN         NaN      NaN      NaN
         16343                  NaN       NaN         NaN      NaN      NaN
         16346                  NaN       NaN         NaN      NaN      NaN

               alt_name:cs short_name      type  geographical_region  \
element  id
relation 16328         NaN        NaN  boundary               Barnim
         16330         NaN        NaN  boundary               Barnim
         16334         NaN        NaN  boundary               Barnim
         16343         NaN        NaN  boundary  Berliner Urstromtal
         16346         NaN        NaN  boundary  Berliner Urstromtal

               ref:DE-BE:OT de:regionalschluessel population:date  \
element  id
relation 16328         1201                   NaN             NaN
         16330         1205                   NaN             NaN
         16334          NaN                 11012      2020-12-31
         16343          NaN                 11005      2020-12-31
         16346         0406                   NaN             NaN

               ref:DE-BE:BEZ  \
element  id
relation 16328           NaN
         16330           NaN
         16334            12
         16343            05
         16346           NaN

                                                source:population  \
element  id
relation 16328                                                NaN
         16330                                                NaN
         16334  https://de.wikipedia.org/wiki/Bezirk_Reinicken...
         16343       https://de.wikipedia.org/wiki/Bezirk_Spandau
         16346                                                NaN

               postal_addr:city postal_addr:country  \
element  id
relation 16328              NaN                 NaN
         16330              NaN                 NaN
         16334              NaN                 NaN
         16343           Berlin                  DE
         16346              NaN                 NaN


In [97]:
districts_clean = districts_gdf[['geometry', 'name', 'admin_level']]
districts_clean.head()

                                                         geometry  \
element  id
relation 16328  POLYGON ((13.30038 52.56998, 13.3019 52.57144,...
         16330  POLYGON ((13.26423 52.62686, 13.26438 52.62802...
         16334  POLYGON ((13.2082 52.59899, 13.20724 52.59987,...
         16343  POLYGON ((13.10932 52.45071, 13.10956 52.45108...
         16346  POLYGON ((13.27034 52.54934, 13.27061 52.54934...

                               name admin_level
element  id
relation 16328        Reinickendorf          10
         16330              Frohnau          10
         16334        Reinickendorf           9
         16343              Spandau           9
         16346  Charlottenburg-Nord          10

In [48]:
districts_clean['geometry'] = districts_clean['geometry'].buffer(0)

/opt/anaconda3/lib/python3.13/site-packages/geopandas/geodataframe.py:1968: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [98]:
import os

# Create the directory structure if it doesn't exist
os.makedirs("spatis/sources", exist_ok=True)

# Now save the file
districts_clean.to_file("spatis/sources/berlin_districts.geojson", driver="GeoJSON")

In [59]:
spatis_gdf = spatis_gdf.to_crs("EPSG:4326")
districts_clean = districts_clean.to_crs("EPSG:4326")

In [60]:
spatis_with_districts = gpd.sjoin(
    spatis_gdf, 
    districts_clean, 
    how="left", 
    predicate="within"
)

In [61]:
spatis_with_districts = spatis_with_districts.rename(
    columns={
        "name_left": "store_name",
        "name_right": "district"
    }
)

In [99]:
spatis_with_districts.to_file("spatis/sources/spatis_with_districts.geojson", driver="GeoJSON")