In [2]:
import sys
!{sys.executable} -m pip install geopy ipython-sql "psycopg[binary]" sqlalchemy

Requirement already satisfied: geopy in /opt/anaconda3/lib/python3.13/site-packages (2.4.1)
Requirement already satisfied: ipython-sql in /opt/anaconda3/lib/python3.13/site-packages (0.5.0)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.39)
Requirement already satisfied: psycopg[binary] in /opt/anaconda3/lib/python3.13/site-packages (3.2.12)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/anaconda3/lib/python3.13/site-packages (from geopy) (2.1)
Requirement already satisfied: prettytable in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (8.30.0)
Requirement already satisfied: sqlparse in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (0.5.3)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: psycopg-binary==3.2.12 in /opt/anaconda3/lib/python3.13/site-packages (from psycopg[binary]) (3.2.12)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack-data in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (4.8.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.13/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/anaconda3/lib/python3.13/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.13/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing in /opt/anaconda3/lib/python3.13/site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in /opt/anaconda3/lib/python3.13/site-packages (from stack-data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure-eval in /opt/anaconda3/lib/python3.13/site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

In [3]:
import sys
!{sys.executable} -m pip install geopy
!{sys.executable} -m pip install ipython-sql
!{sys.executable} -m pip install "psycopg[binary]"
!{sys.executable} -m pip install sqlalchemy

Requirement already satisfied: geopy in /opt/anaconda3/lib/python3.13/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/anaconda3/lib/python3.13/site-packages (from geopy) (2.1)
Requirement already satisfied: ipython-sql in /opt/anaconda3/lib/python3.13/site-packages (0.5.0)
Requirement already satisfied: prettytable in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (8.30.0)
Requirement already satisfied: sqlalchemy>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (2.0.39)
Requirement already satisfied: sqlparse in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (0.5.3)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.12.2)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack-data in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (4.8.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.13/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/anaconda3/lib/python3.13/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.13/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing in /opt/anaconda3/lib/python3.13/site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in /opt/anaconda3/lib/python3.13/site-packages (from stack-data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure-eval in /opt/anaconda3/lib/python3.13/site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Requirement already satisfied: psycopg[binary] in /opt/anaconda3/lib/python3.13/site-packages (3.2.12)
Requirement already satisfied: psycopg-binary==3.2.12 in /opt/anaconda3/lib/python3.13/site-packages (from psycopg[binary]) (3.2.12)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.39)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)

In [4]:
%load_ext sql

In [5]:
%sql postgresql+psycopg2://neondb_owner:a9Am7Yy5r9_T7h4OF2GN@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require

In [6]:
%%sql
CREATE TABLE IF NOT EXISTS test_berlin_data.petstores_final AS
SELECT * FROM public.petstores_final;

 * postgresql+psycopg2://neondb_owner:***@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
(psycopg2.errors.UndefinedTable) relation "public.petstores_final" does not exist
LINE 2: SELECT * FROM public.petstores_final;
                      ^

[SQL: CREATE TABLE IF NOT EXISTS test_berlin_data.petstores_final AS
SELECT * FROM public.petstores_final;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [7]:
%%sql
DROP TABLE public.petstores_final;

 * postgresql+psycopg2://neondb_owner:***@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
(psycopg2.errors.UndefinedTable) table "petstores_final" does not exist

[SQL: DROP TABLE public.petstores_final;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [8]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "postgresql+psycopg2://neondb_owner:a9Am7Yy5r9_T7h4OF2GN@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require"
)

df = pd.read_sql("SELECT * FROM test_berlin_data.petstores_final LIMIT 5", engine)
df

,district_id,name,brand,opening_hours,phone,website,full_address,longitude,latitude,district,neighborhood,id
0,11004004,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-19:00,None,None,"Fressnapf, Lützenstraße, Halensee, Charlottenb...",13.288411,52.499735,Charlottenburg-Wilmersdorf,Halensee,1
1,11001001,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-18:00,None,None,"Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...",13.367520,52.542519,Mitte,Wedding,2
2,11003003,Fressnapf,Fressnapf,None,None,None,"Fressnapf, 128b, Storkower Straße, Blumenviert...",13.451963,52.533614,Pankow,Prenzlauer Berg,3
3,11004004,Lucas Tierwelt,None,Mo-Sa 08:00-20:00,None,https://www.lucas-tierwelt.de/,"Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...",13.308440,52.478876,Charlottenburg-Wilmersdorf,Schmargendorf,4
4,11008008,Das Futterhaus,Das Futterhaus,None,None,None,"Das Futterhaus, 52, Lahnstraße, Richardkiez, N...",13.448016,52.468671,Neukölln,Neukölln,5

In [9]:
%%sql
ALTER TABLE test_berlin_data.petstores_final
ADD COLUMN id SERIAL PRIMARY KEY;

 * postgresql+psycopg2://neondb_owner:***@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
(psycopg2.errors.DuplicateColumn) column "id" of relation "petstores_final" already exists

[SQL: ALTER TABLE test_berlin_data.petstores_final
ADD COLUMN id SERIAL PRIMARY KEY;]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [10]:
df2 = pd.read_sql("SELECT * FROM test_berlin_data.districts LIMIT 5", engine)
df2

  district_id                    district
0    11012012               Reinickendorf
1    11004004  Charlottenburg-Wilmersdorf
2    11009009            Treptow-Köpenick
3    11003003                      Pankow
4    11008008                    Neukölln

In [11]:
df3 = pd.read_sql("SELECT * FROM test_berlin_data.neighborhoods LIMIT 5", engine)
df3

  district_id district neighborhood_id  neighborhood
0    11001001    Mitte            0101         Mitte
1    11001001    Mitte            0102        Moabit
2    11001001    Mitte            0103  Hansaviertel
3    11001001    Mitte            0104    Tiergarten
4    11001001    Mitte            0105       Wedding

In [12]:
%%sql
ALTER TABLE test_berlin_data.petstores_final
ADD CONSTRAINT fk_district
FOREIGN KEY (district_id)
REFERENCES test_berlin_data.districts(district_id);

 * postgresql+psycopg2://neondb_owner:***@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
(psycopg2.errors.DuplicateObject) constraint "fk_district" for relation "petstores_final" already exists

[SQL: ALTER TABLE test_berlin_data.petstores_final
ADD CONSTRAINT fk_district
FOREIGN KEY (district_id)
REFERENCES test_berlin_data.districts(district_id);]
(Background on this error at: https://sqlalche.me/e/20/f405)

In [13]:
import pandas as pd
import osmnx as ox
import json
import numpy as np

petstores = pd.read_csv("berlin_pet_stores_cleaned.csv")
pd.set_option('display.max_columns', None)

FileNotFoundError: [Errno 2] No such file or directory: 'berlin_pet_stores_cleaned.csv'


In this step, I am importing the libraries that I need for the data work.  

* pandas – to work with tabular data  
* osmnx– to retrieve pet store locations from OpenStreetMap  
* json– because some OSM data can come in JSON format  
* numpy – for basic numerical operations

I also used pd.set_option('display.max_columns', None) to make sure Jupyter displays all columns without hiding or truncating them.

In [ ]:
import geopandas as gpd
from shapely.geometry import Point

districts = gpd.read_file("../../districts/sources/districts_enhanced.geojson")
neighborhoods = gpd.read_file("../../districts/sources/neighborhoods_enhanced.geojson")

districts.head(), neighborhoods.head()

(  district_id                    district  \
 0          12               Reinickendorf
 1          04  Charlottenburg-Wilmersdorf
 2          09            Treptow-Köpenick
 3          03                      Pankow
 4          08                    Neukölln

                                             geometry
 0  MULTIPOLYGON (((13.32074 52.6266, 13.32045 52....
 1  MULTIPOLYGON (((13.32111 52.52446, 13.32103 52...
 2  MULTIPOLYGON (((13.57925 52.39083, 13.57958 52...
 3  MULTIPOLYGON (((13.50481 52.6196, 13.50467 52....
 4  MULTIPOLYGON (((13.45832 52.48569, 13.45823 52...  ,
   district_id district  neighborhood  \
 0          01    Mitte         Mitte
 1          01    Mitte        Moabit
 2          01    Mitte  Hansaviertel
 3          01    Mitte    Tiergarten
 4          01    Mitte       Wedding

                                             geometry
 0  POLYGON ((13.41649 52.52696, 13.41635 52.52702...
 1  POLYGON ((13.33884 52.51974, 13.33884 52.51974...
 2  POLYGON ((13.34322 52.51557, 13.34323 52.51557...
 3  POLYGON ((13.36879 52.49878, 13.36891 52.49877...
 4  POLYGON ((13.34656 52.53879, 13.34664 52.53878...  )

Here, I load the GeoJSON files for districts and neighborhoods.
These layers provide the administrative boundaries of Berlin and are necessary for the spatial join that assigns the correct district_id and neighborhood to each pet store based on its coordinates.

In [ ]:
from shapely.geometry import Point

petstores['geometry'] = petstores.apply(
    lambda row: Point(row['longitude'], row['latitude']),
    axis=1
)

petstores_gdf = gpd.GeoDataFrame(
    petstores,
    geometry='geometry',
    crs="EPSG:4326"
)

petstores_gdf.head()

,geometry,district_id,name,brand,opening_hours,phone,website,full_address,longitude,latitude
0,POINT (13.28841 52.49974),11004004,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-19:00,NaN,NaN,"Fressnapf, Lützenstraße, Halensee, Charlottenb...",13.288411,52.499735
1,POINT (13.36752 52.54252),11001001,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-18:00,NaN,NaN,"Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...",13.367520,52.542519
2,POINT (13.45196 52.53361),11003003,Fressnapf,Fressnapf,NaN,NaN,NaN,"Fressnapf, 128b, Storkower Straße, Blumenviert...",13.451963,52.533614
3,POINT (13.30844 52.47888),11004004,Lucas Tierwelt,NaN,Mo-Sa 08:00-20:00,NaN,https://www.lucas-tierwelt.de/,"Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...",13.308440,52.478876
4,POINT (13.44802 52.46867),11008008,Das Futterhaus,Das Futterhaus,NaN,NaN,NaN,"Das Futterhaus, 52, Lahnstraße, Richardkiez, N...",13.448016,52.468671

In this step, I convert the latitude and longitude values into actual Point geometry objects.
Then I create a GeoDataFrame (petstores_gdf) with the correct CRS (EPSG:4326).
This prepares the dataset for the spatial join with Berlin’s district and neighborhood boundaries.

In [ ]:
petstores_with_districts = gpd.sjoin(
    petstores_gdf,
    districts[['district_id', 'district', 'geometry']],
    how="left",
    predicate='within'
)

petstores_with_districts.head()

,geometry,district_id_left,name,brand,opening_hours,phone,website,full_address,longitude,latitude,index_right,district_id_right,district
0,POINT (13.28841 52.49974),11004004,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-19:00,NaN,NaN,"Fressnapf, Lützenstraße, Halensee, Charlottenb...",13.288411,52.499735,1,04,Charlottenburg-Wilmersdorf
1,POINT (13.36752 52.54252),11001001,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-18:00,NaN,NaN,"Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...",13.367520,52.542519,9,01,Mitte
2,POINT (13.45196 52.53361),11003003,Fressnapf,Fressnapf,NaN,NaN,NaN,"Fressnapf, 128b, Storkower Straße, Blumenviert...",13.451963,52.533614,3,03,Pankow
3,POINT (13.30844 52.47888),11004004,Lucas Tierwelt,NaN,Mo-Sa 08:00-20:00,NaN,https://www.lucas-tierwelt.de/,"Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...",13.308440,52.478876,1,04,Charlottenburg-Wilmersdorf
4,POINT (13.44802 52.46867),11008008,Das Futterhaus,Das Futterhaus,NaN,NaN,NaN,"Das Futterhaus, 52, Lahnstraße, Richardkiez, N...",13.448016,52.468671,4,08,Neukölln

Here, I perform a spatial join between my pet store points and the Berlin district boundaries.
By using predicate='within', each store is assigned the correct district_id and district name based on its location.
This confirms that my geometry and CRS setup is working properly.

In [ ]:
petstores_with_districts = petstores_with_districts.drop(columns=['index_right'])

Here, I drop the index_right column that was automatically added during the spatial join.
Since I don’t need it for the final dataset, I remove it to keep the table clean and organized.

In [ ]:
petstores_with_neighborhoods = gpd.sjoin(
    petstores_with_districts,
    neighborhoods[['district_id', 'neighborhood', 'geometry']],
    how="left",
    predicate='within'
)

petstores_with_neighborhoods.head()

,geometry,district_id_left,name,brand,opening_hours,phone,website,full_address,longitude,latitude,district_id_right,district,index_right,district_id,neighborhood
0,POINT (13.28841 52.49974),11004004,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-19:00,NaN,NaN,"Fressnapf, Lützenstraße, Halensee, Charlottenb...",13.288411,52.499735,04,Charlottenburg-Wilmersdorf,27,04,Halensee
1,POINT (13.36752 52.54252),11001001,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-18:00,NaN,NaN,"Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...",13.367520,52.542519,01,Mitte,4,01,Wedding
2,POINT (13.45196 52.53361),11003003,Fressnapf,Fressnapf,NaN,NaN,NaN,"Fressnapf, 128b, Storkower Straße, Blumenviert...",13.451963,52.533614,03,Pankow,8,03,Prenzlauer Berg
3,POINT (13.30844 52.47888),11004004,Lucas Tierwelt,NaN,Mo-Sa 08:00-20:00,NaN,https://www.lucas-tierwelt.de/,"Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...",13.308440,52.478876,04,Charlottenburg-Wilmersdorf,23,04,Schmargendorf
4,POINT (13.44802 52.46867),11008008,Das Futterhaus,Das Futterhaus,NaN,NaN,NaN,"Das Futterhaus, 52, Lahnstraße, Richardkiez, N...",13.448016,52.468671,08,Neukölln,50,08,Neukölln

In this step, I perform a spatial join between the pet stores (already matched with districts) and the Berlin neighborhood boundaries.
Using predicate='within', each store is assigned the correct neighborhood name and corresponding district_id based on its location.
This ensures that both district and neighborhood mappings are fully complete.

In [ ]:
petstores_final = petstores_with_neighborhoods.rename(columns={
    'district_id_left': 'district_id'
})

cols_to_drop = [
    'geometry',            
    'geometry_y',          
    'geometry_x',          
    'district_id_right'    
]

cols_to_drop = [c for c in cols_to_drop if c in petstores_final.columns]

petstores_final = petstores_final.drop(columns=cols_to_drop)

petstores_final.head()

,district_id,name,brand,opening_hours,phone,website,full_address,longitude,latitude,district,index_right,district_id,neighborhood
0,11004004,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-19:00,NaN,NaN,"Fressnapf, Lützenstraße, Halensee, Charlottenb...",13.288411,52.499735,Charlottenburg-Wilmersdorf,27,04,Halensee
1,11001001,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-18:00,NaN,NaN,"Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...",13.367520,52.542519,Mitte,4,01,Wedding
2,11003003,Fressnapf,Fressnapf,NaN,NaN,NaN,"Fressnapf, 128b, Storkower Straße, Blumenviert...",13.451963,52.533614,Pankow,8,03,Prenzlauer Berg
3,11004004,Lucas Tierwelt,NaN,Mo-Sa 08:00-20:00,NaN,https://www.lucas-tierwelt.de/,"Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...",13.308440,52.478876,Charlottenburg-Wilmersdorf,23,04,Schmargendorf
4,11008008,Das Futterhaus,Das Futterhaus,NaN,NaN,NaN,"Das Futterhaus, 52, Lahnstraße, Richardkiez, N...",13.448016,52.468671,Neukölln,50,08,Neukölln

In this step, I rename district_id_left to district_id so the final dataset has a clear and consistent structure.
I also remove all geometry-related columns (geometry, geometry_x, geometry_y, district_id_right) that were created during the spatial joins but are not needed in the final table.
This gives me a clean and well-structured dataframe, ready for validation and loading.

In [ ]:
petstores_final = petstores_final.drop(columns=['index_right'])
petstores_final.head()

,district_id,name,brand,opening_hours,phone,website,full_address,longitude,latitude,district,district_id,neighborhood
0,11004004,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-19:00,NaN,NaN,"Fressnapf, Lützenstraße, Halensee, Charlottenb...",13.288411,52.499735,Charlottenburg-Wilmersdorf,04,Halensee
1,11001001,Fressnapf,Fressnapf,Mo-Fr 09:00-20:00; Sa 09:00-18:00,NaN,NaN,"Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...",13.367520,52.542519,Mitte,01,Wedding
2,11003003,Fressnapf,Fressnapf,NaN,NaN,NaN,"Fressnapf, 128b, Storkower Straße, Blumenviert...",13.451963,52.533614,Pankow,03,Prenzlauer Berg
3,11004004,Lucas Tierwelt,NaN,Mo-Sa 08:00-20:00,NaN,https://www.lucas-tierwelt.de/,"Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...",13.308440,52.478876,Charlottenburg-Wilmersdorf,04,Schmargendorf
4,11008008,Das Futterhaus,Das Futterhaus,NaN,NaN,NaN,"Das Futterhaus, 52, Lahnstraße, Richardkiez, N...",13.448016,52.468671,Neukölln,08,Neukölln

Here, I drop the index_right column, which was added automatically during the spatial join.
Since I don’t need this column for the final dataset, I remove it to keep the dataframe clean and consistent.

In [ ]:
petstores_final.columns

Index(['district_id', 'name', 'brand', 'opening_hours', 'phone', 'website',
       'full_address', 'longitude', 'latitude', 'district', 'district_id',
       'neighborhood'],
      dtype='object')

Here, I quickly check all column names in the petstores_final dataframe.
This helps me confirm that the cleaned dataset has the correct schema and all expected fields are present before validation and loading.

In [ ]:
%%sql
postgresql+psycopg://nuran_nalci:LSGPrTr27Rllc3TT40iq@localhost:5433/layereddb

In this cell, I connect to my local PostgreSQL database using the SQL magic command.
This allows me to run SQL queries directly from the notebook during my validation checks.

In [ ]:
%%sql
CREATE TABLE IF NOT EXISTS pet_stores (
    district_id VARCHAR(10),
    name VARCHAR(200),
    brand VARCHAR(200),
    opening_hours VARCHAR(200),
    phone VARCHAR(100),
    website VARCHAR(300),
    full_address VARCHAR(300),
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION,
    district VARCHAR(100),
    neighborhood VARCHAR(100)
);

 * postgresql+psycopg://nuran_nalci:***@localhost:5433/layereddb
Done.

[]

In this cell, I define the structure of the pet_stores table.
I specify all the necessary columns (such as district, neighborhood, coordinates, contact details, etc.) to ensure the final dataset has a clear and consistent schema.
This table will be used for testing how the data loads into the database.

In [ ]:
%%sql
INSERT INTO pet_stores (
    district_id, name, brand, opening_hours,
    phone, website, full_address, longitude, latitude,
    district, neighborhood
)
VALUES (
    '04',
    'Fressnapf',
    'Fressnapf',
    'Mo-Fr 09:00-20:00; Sa 09:00-19:00',
    NULL,
    NULL,
    'Fressnapf, Berlin',
    13.288411,
    52.499735,
    'Charlottenburg-Wilmersdorf',
    'Halensee'
);

 * postgresql+psycopg://nuran_nalci:***@localhost:5433/layereddb
1 rows affected.

[]

In this cell, I insert a single test record into the pet_stores table.
I use this step only to confirm that the table structure works correctly and that the insert operation succeeds without any constraint issues.

In [ ]:
from geopy.geocoders import Nominatim
import time

In [ ]:
tags = {"shop": "pet"}
petstores_gdf = ox.features_from_place("Berlin, Germany", tags=tags)
petstores_gdf.head()

                                    geometry           brand brand:wikidata  \
element id
node    111810614  POINT (13.28841 52.49974)       Fressnapf        Q875796
        346138343  POINT (13.36752 52.54252)       Fressnapf        Q875796
        417360251  POINT (13.45196 52.53361)       Fressnapf        Q875796
        438385039  POINT (13.30844 52.47888)             NaN            NaN
        446899194  POINT (13.44802 52.46867)  Das Futterhaus       Q1167914

                     brand:wikipedia  check_date check_date:opening_hours  \
element id
node    111810614       en:Fressnapf  2025-10-29               2025-10-29
        346138343       de:Fressnapf  2025-08-28               2025-08-28
        417360251       en:Fressnapf         NaN                      NaN
        438385039                NaN         NaN                      NaN
        446899194  de:Das Futterhaus         NaN                      NaN

                             name                      opening_hours shop  \
element id
node    111810614       Fressnapf  Mo-Fr 09:00-20:00; Sa 09:00-19:00  pet
        346138343       Fressnapf  Mo-Fr 09:00-20:00; Sa 09:00-18:00  pet
        417360251       Fressnapf                                NaN  pet
        438385039  Lucas Tierwelt                  Mo-Sa 08:00-20:00  pet
        446899194  Das Futterhaus                                NaN  pet

                  addr:housenumber        addr:street level wheelchair  \
element id
node    111810614              NaN                NaN   NaN        NaN
        346138343            10-11       Müllerstraße     0        yes
        417360251             128b   Storkower Straße   NaN    limited
        438385039               95  Forckenbeckstraße   NaN        NaN
        446899194              NaN                NaN   NaN        NaN

                  addr:city addr:country addr:postcode      addr:suburb  \
element id
node    111810614       NaN          NaN           NaN              NaN
        346138343       NaN          NaN           NaN              NaN
        417360251    Berlin           DE         10407  Prenzlauer Berg
        438385039    Berlin           DE         14199    Schmargendorf
        446899194       NaN          NaN           NaN              NaN

                  toilets:wheelchair  \
element id
node    111810614                NaN
        346138343                NaN
        417360251                 no
        438385039                NaN
        446899194                NaN

                                              wheelchair:description  \
element id
node    111810614                                                NaN
        346138343                                                NaN
        417360251  Behindertenparkplätze werden dauerhaft als Abs...
        438385039                                                NaN
        446899194                                                NaN

                                          website  pet phone email  \
element id
node    111810614                             NaN  NaN   NaN   NaN
        346138343                             NaN  NaN   NaN   NaN
        417360251                             NaN  NaN   NaN   NaN
        438385039  https://www.lucas-tierwelt.de/  NaN   NaN   NaN
        446899194                             NaN  NaN   NaN   NaN

                  payment:american_express payment:coins payment:mastercard  \
element id
node    111810614                      NaN           NaN                NaN
        346138343                      NaN           NaN                NaN
        417360251                      NaN           NaN                NaN
        438385039                      NaN           NaN                NaN
        446899194                      NaN           NaN                NaN

                  payment:notes payment:visa contact:email contact:fax  \
element id
node    111810614           NaN          NaN           NaN         NaN
        346138343           NaN          NaN           NaN         NaN
        417360251           NaN          NaN           NaN         NaN
        438385039           NaN          NaN           NaN         NaN
        446899194           NaN          NaN           NaN         NaN

                  contact:phone contact:website note operator  fax  \
element id
node    111810614           NaN             NaN  NaN      NaN  NaN
        346138343           NaN             NaN  NaN      NaN  NaN
        417360251           NaN             NaN  NaN      NaN  NaN
        438385039           NaN             NaN  NaN      NaN  NaN
        446899194           NaN             NaN  NaN      NaN  NaN

                  payment:credit_cards payment:debit_cards post_office  \
element id
node    111810614                  NaN                 NaN         NaN
        346138343                  NaN                 NaN         NaN
        417360251                  NaN                 NaN         NaN
        438385039                  NaN                 NaN         NaN
        446899194                  NaN                 NaN         NaN

                  post_office:brand post_office:brand:wikidata  \
element id
node    111810614               NaN                        NaN
        346138343               NaN                        NaN
        417360251               NaN                        NaN
        438385039               NaN                        NaN
        446899194               NaN                        NaN

                  payment:girocard source contact:facebook delivery  \
element id
node    111810614              NaN    NaN              NaN      NaN
        346138343              NaN    NaN              NaN      NaN
        417360251              NaN    NaN              NaN      NaN
        438385039              NaN    NaN              NaN      NaN
        446899194              NaN    NaN              NaN      NaN

                  description species:de addr:inclusion contact:instagram  \
element id
node    111810614         NaN        NaN            NaN               NaN
        346138343         NaN        NaN            NaN               NaN
        417360251         NaN        NaN            NaN               NaN
        438385039         NaN        NaN            NaN               NaN
        446899194         NaN        NaN            NaN               NaN

                  ref:vatin dispensing opening_hours:covid19 old_name  \
element id
node    111810614       NaN        NaN                   NaN      NaN
        346138343       NaN        NaN                   NaN      NaN
        417360251       NaN        NaN                   NaN      NaN
        438385039       NaN        NaN                   NaN      NaN
        446899194       NaN        NaN                   NaN      NaN

                  wikimedia_commons surveillance start_date  \
element id
node    111810614               NaN          NaN        NaN
        346138343               NaN          NaN        NaN
        417360251               NaN          NaN        NaN
        438385039               NaN          NaN        NaN
        446899194               NaN          NaN        NaN

                  opening_hours:signed organic post_office:ref  \
element id
node    111810614                  NaN     NaN             NaN
        346138343                  NaN     NaN             NaN
        417360251                  NaN     NaN             NaN
        438385039                  NaN     NaN             NaN
        446899194                  NaN     NaN             NaN

                  post_office:type  url alt_name building roof:shape  \
element id
node    111810614              NaN  NaN      NaN      NaN        NaN
        346138343              NaN  NaN      NaN      NaN        NaN
        417360251              NaN  NaN      NaN      NaN        NaN
        438385039              NaN  NaN      NaN      NaN        NaN
        446899194              NaN  NaN      NaN      NaN        NaN

                  building:colour building:levels payment:cash roof:levels  \
element id
node    111810614             NaN             NaN          NaN         NaN
        346138343             NaN             NaN          NaN         NaN
        417360251             NaN             NaN          NaN         NaN
        438385039             NaN             NaN          NaN         NaN
        446899194             NaN             NaN          NaN         NaN

                  indoor room entrance
element id
node    111810614    NaN  NaN      NaN
        346138343    NaN  NaN      NaN
        417360251    NaN  NaN      NaN
        438385039    NaN  NaN      NaN
        446899194    NaN  NaN      NaN

Here, I am retrieving pet shop locations in Berlin from OpenStreetMap.

* tags = {"shop": "pet"} selects only pet store locations  
* ox.features_from_place("Berlin, Germany", tags=tags) gets pet shops located in Berlin
* "Berlin, Germany" the place boundary used for the OSM query. 
* petstores_gdf.head() displays the first few rows to verify the data loaded correctly

In [ ]:
neighborhoods = gpd.read_file("../../districts/sources/neighborhoods_enhanced.geojson")

print(neighborhoods.columns)

if "index_right" in petstores_gdf.columns:
    petstores_gdf = petstores_gdf.drop(columns=["index_right"])

petstores_gdf = gpd.sjoin(
    petstores_gdf,
    neighborhoods[["district", "neighborhood", "geometry"]],
    how="left",
    predicate="within",
    lsuffix="left",
    rsuffix="right"
)

petstores_gdf = petstores_gdf.rename(columns={
    "district_right": "district",
    "neighborhood_right": "neighborhood"
})

if "district_left" in petstores_gdf.columns:
    petstores_gdf = petstores_gdf.drop(columns=["district_left"])
if "neighborhood_left" in petstores_gdf.columns:
    petstores_gdf = petstores_gdf.drop(columns=["neighborhood_left"])

district_mapping = {
    'Mitte': '11001001',
    'Friedrichshain-Kreuzberg': '11002002',
    'Pankow': '11003003',
    'Charlottenburg-Wilmersdorf': '11004004',
    'Spandau': '11005005',
    'Steglitz-Zehlendorf': '11006006',
    'Tempelhof-Schöneberg': '11007007',
    'Neukölln': '11008008',
    'Treptow-Köpenick': '11009009',
    'Marzahn-Hellersdorf': '11010010',
    'Lichtenberg': '11011011',
    'Reinickendorf': '11012012'
}

petstores_gdf["district_id"] = petstores_gdf["district"].map(district_mapping)

Index(['district_id', 'district', 'neighborhood', 'geometry'], dtype='object')

In this step, I implemented the spatial join and applied the official district mapping to ensure consistency across the dataset.

What was done:

1-Loaded the neighborhoods layer (neighborhoods_enhanced.geojson)
This file contains the polygons for each neighborhood in Berlin and the corresponding district names.

2-Cleaned old spatial join artifacts
Removed index_right and potential leftover duplicate columns to avoid errors and ensure a clean join.

3-Performed a spatial join using predicate="within"
The pet store points were matched with the neighborhood polygons to determine:

-the correct district (name)
-the correct neighborhood (name)
-Only the necessary columns (district, neighborhood, geometry) were used to avoid inconsistent ID formats.

4-Renamed suffix columns
Reformatted district_right -> district and neighborhood_right -> neighborhood
This keeps the table clean and readable.

5-Applied the official district_id mapping
Using the dictionary provided in the mapping folder, each district name was mapped to the official Berlin district ID.This ensures full consistency with the project structure and other layers.

Result:
The dataset now contains:
-accurate spatial neighborhood assignments
-correct district names
-and standardized district_id values matching the official project mapping Fully aligned with the expected Layered project structure.

In [ ]:
neighborhoods.head()

,district_id,district,neighborhood,geometry
0,01,Mitte,Mitte,"POLYGON ((13.41649 52.52696, 13.41635 52.52702..."
1,01,Mitte,Moabit,"POLYGON ((13.33884 52.51974, 13.33884 52.51974..."
2,01,Mitte,Hansaviertel,"POLYGON ((13.34322 52.51557, 13.34323 52.51557..."
3,01,Mitte,Tiergarten,"POLYGON ((13.36879 52.49878, 13.36891 52.49877..."
4,01,Mitte,Wedding,"POLYGON ((13.34656 52.53879, 13.34664 52.53878..."

In [ ]:
print("Current CRS:", petstores_gdf.crs)

Current CRS: epsg:4326

In [ ]:
print("Current CRS:", petstores_gdf.crs)


if petstores_gdf.crs != "EPSG:4326":
    petstores_gdf = petstores_gdf.to_crs(epsg=4326)
    print("CRS converted to EPSG:4326 (WGS 84)")

invalid_geometries = petstores_gdf[~petstores_gdf.is_valid]
print(f"Invalid geometries found: {len(invalid_geometries)}")

petstores_gdf = petstores_gdf.drop_duplicates(subset='geometry')

print("Geospatial validation completed successfully.")

Current CRS: epsg:4326
Invalid geometries found: 0
Geospatial validation completed successfully.

Validate and Clean Geospatial Data
* I confirmed that all geometries are valid and the coordinate reference system is EPSG:4326 (WGS 84), which is the standard for Berlin data.
No invalid geometries or duplicates were found, ensuring that the dataset is spatially accurate and ready for further cleaning and transformation.

In [ ]:
petstores_gdf.columns.tolist()

['geometry',
 'brand',
 'brand:wikidata',
 'brand:wikipedia',
 'check_date',
 'check_date:opening_hours',
 'name',
 'opening_hours',
 'shop',
 'addr:housenumber',
 'addr:street',
 'level',
 'wheelchair',
 'addr:city',
 'addr:country',
 'addr:postcode',
 'addr:suburb',
 'toilets:wheelchair',
 'wheelchair:description',
 'website',
 'pet',
 'phone',
 'email',
 'payment:american_express',
 'payment:coins',
 'payment:mastercard',
 'payment:notes',
 'payment:visa',
 'contact:email',
 'contact:fax',
 'contact:phone',
 'contact:website',
 'note',
 'operator',
 'fax',
 'payment:credit_cards',
 'payment:debit_cards',
 'post_office',
 'post_office:brand',
 'post_office:brand:wikidata',
 'payment:girocard',
 'source',
 'contact:facebook',
 'delivery',
 'description',
 'species:de',
 'addr:inclusion',
 'contact:instagram',
 'ref:vatin',
 'dispensing',
 'opening_hours:covid19',
 'old_name',
 'wikimedia_commons',
 'surveillance',
 'start_date',
 'opening_hours:signed',
 'organic',
 'post_office:ref',
 'post_office:type',
 'url',
 'alt_name',
 'building',
 'roof:shape',
 'building:colour',
 'building:levels',
 'payment:cash',
 'roof:levels',
 'indoor',
 'room',
 'entrance',
 'index_right',
 'district',
 'neighborhood',
 'district_id']

This lists all column names in the dataset to check which attributes are available and what information each represents.

In [ ]:
petstores_gdf.isna().sum().sort_values(ascending=False)

entrance             95
wikimedia_commons    95
payment:girocard     95
contact:fax          95
delivery             95
                     ..
index_right           0
geometry              0
shop                  0
name                  0
district_id           0
Length: 74, dtype: int64

Here I am checking how many missing values each column has.

* .isna() marks missing entries
* .sum() counts how many missing values exist  
* .sort_values() sorts them from most to least  

This helps me understand data quality and decide which columns are useful.

In [ ]:
petstores_gdf = petstores_gdf[petstores_gdf.geometry.type == "Point"].copy()

In [ ]:
petstores_gdf["longitude"] = petstores_gdf.geometry.x
petstores_gdf["latitude"] = petstores_gdf.geometry.y

In [ ]:
geolocator = Nominatim(user_agent="petstore_address_restoration")

def safe_reverse(lat, lon):
    if pd.isna(lat) or pd.isna(lon):
        return None
    try:
        location = geolocator.reverse(f"{lat}, {lon}", timeout=10)
        time.sleep(1)
        return location.address if location else None
    except:
        return None

In [ ]:
petstores_gdf["full_address"] = petstores_gdf.apply(
    lambda row: safe_reverse(row["latitude"], row["longitude"]),
    axis=1
)

In [ ]:
petstores_gdf['full_address'].isna().sum()

np.int64(0)

In [ ]:
keep_cols = [
    'geometry',
    'district_id',
    'name',
    'brand',
    'opening_hours',
    'addr:street',
    'addr:housenumber',
    'addr:postcode',
    'addr:city',
    'phone',
    'website',
    'full_address'
]
petstores_cleaned = petstores_gdf[keep_cols].copy()
petstores_cleaned.head()

                                    geometry district_id            name  \
element id
node    111810614  POINT (13.28841 52.49974)    11004004       Fressnapf
        346138343  POINT (13.36752 52.54252)    11001001       Fressnapf
        417360251  POINT (13.45196 52.53361)    11003003       Fressnapf
        438385039  POINT (13.30844 52.47888)    11004004  Lucas Tierwelt
        446899194  POINT (13.44802 52.46867)    11008008  Das Futterhaus

                            brand                      opening_hours  \
element id
node    111810614       Fressnapf  Mo-Fr 09:00-20:00; Sa 09:00-19:00
        346138343       Fressnapf  Mo-Fr 09:00-20:00; Sa 09:00-18:00
        417360251       Fressnapf                                NaN
        438385039             NaN                  Mo-Sa 08:00-20:00
        446899194  Das Futterhaus                                NaN

                         addr:street addr:housenumber addr:postcode addr:city  \
element id
node    111810614                NaN              NaN           NaN       NaN
        346138343       Müllerstraße            10-11           NaN       NaN
        417360251   Storkower Straße             128b         10407    Berlin
        438385039  Forckenbeckstraße               95         14199    Berlin
        446899194                NaN              NaN           NaN       NaN

                  phone                         website  \
element id
node    111810614   NaN                             NaN
        346138343   NaN                             NaN
        417360251   NaN                             NaN
        438385039   NaN  https://www.lucas-tierwelt.de/
        446899194   NaN                             NaN

                                                        full_address
element id
node    111810614  Fressnapf, Lützenstraße, Halensee, Charlottenb...
        346138343  Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...
        417360251  Fressnapf, 128b, Storkower Straße, Blumenviert...
        438385039  Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...
        446899194  Das Futterhaus, 52, Lahnstraße, Richardkiez, N...

In this step, I manually selected the columns that are actually useful for the project.  
Before choosing, I checked all columns and their missing value counts.  
Some columns were almost completely empty
so they did not add meaningful value to the dataset.

In [ ]:
petstores_cleaned['geometry'] = petstores_cleaned['geometry'].centroid
petstores_cleaned['longitude'] = petstores_cleaned.geometry.x
petstores_cleaned['latitude'] = petstores_cleaned.geometry.y

petstores_cleaned[['name', 'full_address', 'latitude', 'longitude']].head()

/var/folders/mn/w43_rvg92n9dv58q76z80hgc0000gn/T/ipykernel_15985/2468793336.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  petstores_cleaned['geometry'] = petstores_cleaned['geometry'].centroid

                             name  \
element id
node    111810614       Fressnapf
        346138343       Fressnapf
        417360251       Fressnapf
        438385039  Lucas Tierwelt
        446899194  Das Futterhaus

                                                        full_address  \
element id
node    111810614  Fressnapf, Lützenstraße, Halensee, Charlottenb...
        346138343  Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...
        417360251  Fressnapf, 128b, Storkower Straße, Blumenviert...
        438385039  Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...
        446899194  Das Futterhaus, 52, Lahnstraße, Richardkiez, N...

                    latitude  longitude
element id
node    111810614  52.499735  13.288411
        346138343  52.542519  13.367520
        417360251  52.533614  13.451963
        438385039  52.478876  13.308440
        446899194  52.468671  13.448016

The geometry field in OSM can sometimes be stored as shapes (polygons).  
However, for mapping and database storage we need a single coordinate point.  

* geometry.centroid extracts the center point of the shape.  
* geometry.x gives the longitude.  
* geometry.y gives the latitude.  

Then I display a preview to verify that the final coordinates were extracted correctly.

In [ ]:
petstores_cleaned = petstores_cleaned.drop(columns=[
    'addr:street', 'addr:housenumber', 'addr:postcode', 'addr:city'
], errors='ignore')

petstores_cleaned.head()

                                    geometry district_id            name  \
element id
node    111810614  POINT (13.28841 52.49974)    11004004       Fressnapf
        346138343  POINT (13.36752 52.54252)    11001001       Fressnapf
        417360251  POINT (13.45196 52.53361)    11003003       Fressnapf
        438385039  POINT (13.30844 52.47888)    11004004  Lucas Tierwelt
        446899194  POINT (13.44802 52.46867)    11008008  Das Futterhaus

                            brand                      opening_hours phone  \
element id
node    111810614       Fressnapf  Mo-Fr 09:00-20:00; Sa 09:00-19:00   NaN
        346138343       Fressnapf  Mo-Fr 09:00-20:00; Sa 09:00-18:00   NaN
        417360251       Fressnapf                                NaN   NaN
        438385039             NaN                  Mo-Sa 08:00-20:00   NaN
        446899194  Das Futterhaus                                NaN   NaN

                                          website  \
element id
node    111810614                             NaN
        346138343                             NaN
        417360251                             NaN
        438385039  https://www.lucas-tierwelt.de/
        446899194                             NaN

                                                        full_address  \
element id
node    111810614  Fressnapf, Lützenstraße, Halensee, Charlottenb...
        346138343  Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...
        417360251  Fressnapf, 128b, Storkower Straße, Blumenviert...
        438385039  Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...
        446899194  Das Futterhaus, 52, Lahnstraße, Richardkiez, N...

                   longitude   latitude
element id
node    111810614  13.288411  52.499735
        346138343  13.367520  52.542519
        417360251  13.451963  52.533614
        438385039  13.308440  52.478876
        446899194  13.448016  52.468671

Since the full address has already been combined into the full_address column,  
the original address fields (addr:street, addr:housenumber, addr:postcode, addr:city) are no longer needed.  

Therefore, I remove them using drop().  
The parameter errors="ignore" ensures that the code does not fail in case any of these columns are missing.

In [ ]:
petstores_cleaned.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
MultiIndex: 82 entries, ('node', np.int64(111810614)) to ('node', np.int64(13064860585))
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   geometry       82 non-null     geometry
 1   district_id    82 non-null     object
 2   name           82 non-null     object
 3   brand          38 non-null     object
 4   opening_hours  65 non-null     object
 5   phone          17 non-null     object
 6   website        24 non-null     object
 7   full_address   82 non-null     object
 8   longitude      82 non-null     float64
 9   latitude       82 non-null     float64
dtypes: float64(2), geometry(1), object(7)
memory usage: 9.6+ KB

This allows me to verify:
* Number of rows and columns  
* Which columns still contain missing values  
* Data types  

It’s a quick validation step to make sure the cleaning worked properly.

In [ ]:
petstores_cleaned.head(20)

                                     geometry district_id  \
element id
node    111810614   POINT (13.28841 52.49974)    11004004
        346138343   POINT (13.36752 52.54252)    11001001
        417360251   POINT (13.45196 52.53361)    11003003
        438385039   POINT (13.30844 52.47888)    11004004
        446899194   POINT (13.44802 52.46867)    11008008
        701825313   POINT (13.32671 52.49079)    11004004
        800755193     POINT (13.3535 52.5746)    11012012
        861870108   POINT (13.61083 52.54018)    11010010
        1112653257  POINT (13.24238 52.42322)    11006006
        1157588586   POINT (13.3666 52.56424)    11012012
        1198087358  POINT (13.19667 52.53016)    11005005
        1311479655  POINT (13.30647 52.52553)    11004004
        1427998890  POINT (13.12883 52.52843)    11005005
        1457600608  POINT (13.37072 52.56473)    11012012
        1498303230  POINT (13.55979 52.50635)    11010010
        1511328799   POINT (13.4244 52.48789)    11002002
        1608667951  POINT (13.38438 52.50312)    11002002
        1643105094  POINT (13.33338 52.59533)    11012012
        1774557661  POINT (13.34222 52.46893)    11007007
        1779217862  POINT (13.50724 52.49925)    11011011

                                      name           brand  \
element id
node    111810614                Fressnapf       Fressnapf
        346138343                Fressnapf       Fressnapf
        417360251                Fressnapf       Fressnapf
        438385039           Lucas Tierwelt             NaN
        446899194           Das Futterhaus  Das Futterhaus
        701825313           Natürlich Hund             NaN
        800755193               Hundesalon             NaN
        861870108                Fressnapf       Fressnapf
        1112653257               Fressnapf       Fressnapf
        1157588586          Das Futterhaus  Das Futterhaus
        1198087358               Fressnapf       Fressnapf
        1311479655            Zoo fridolin             NaN
        1427998890               Fressnapf       Fressnapf
        1457600608               Fressnapf       Fressnapf
        1498303230          Das Futterhaus  Das Futterhaus
        1511328799          Das Futterhaus  Das Futterhaus
        1608667951               Fressnapf       Fressnapf
        1643105094  Marine Aquarium Senior             NaN
        1774557661      Steffis Futterkeks             NaN
        1779217862               Fressnapf       Fressnapf

                                                        opening_hours  \
element id
node    111810614                   Mo-Fr 09:00-20:00; Sa 09:00-19:00
        346138343                   Mo-Fr 09:00-20:00; Sa 09:00-18:00
        417360251                                                 NaN
        438385039                                   Mo-Sa 08:00-20:00
        446899194                                                 NaN
        701825313                   Tu-Fr 11:00-18:00; Sa 10:00-15:00
        800755193   "nach Vereinbarung (Beschriftung der Öffnungsz...
        861870108           Mo-Fr 09:00-20:00; Sa 09:00-18:00; PH off
        1112653257                                                NaN
        1157588586                                             closed
        1198087358                       Mo-Sa 09:00-20:00; Su,PH off
        1311479655  Mo-Fr 09:00-18:00; Sa 09:00-14:00; Su off, PH off
        1427998890                                                NaN
        1457600608                  Mo-Fr 09:00-20:00; Sa 09:00-18:00
        1498303230                                                NaN
        1511328799                                  Mo-Sa 10:00-20:00
        1608667951                  Mo-Fr 09:00-20:00; Sa 09:00-18:00
        1643105094                                  Mo-Sa 10:00-18:00
        1774557661  Mo-Th 09:00-12:00,14:00-18:00; Fr 09:00-12:00,...
        1779217862                  Mo-Fr 09:00-20:00; Sa 09:00-19:00

                              phone  \
element id
node    111810614               NaN
        346138343               NaN
        417360251               NaN
        438385039               NaN
        446899194               NaN
        701825313               NaN
        800755193   +49 30 81612547
        861870108   +49 30 99275073
        1112653257              NaN
        1157588586              NaN
        1198087358              NaN
        1311479655              NaN
        1427998890              NaN
        1457600608  +49 30 43724675
        1498303230              NaN
        1511328799    +493061209038
        1608667951              NaN
        1643105094  +49 30 40910702
        1774557661              NaN
        1779217862  +49 30 50018185

                                                              website  \
element id
node    111810614                                                 NaN
        346138343                                                 NaN
        417360251                                                 NaN
        438385039                      https://www.lucas-tierwelt.de/
        446899194                                                 NaN
        701825313                                                 NaN
        800755193                                                 NaN
        861870108   https://www.fressnapf.de/stores/fressnapf-berl...
        1112653257                                                NaN
        1157588586                                                NaN
        1198087358                                                NaN
        1311479655                                                NaN
        1427998890                                                NaN
        1457600608                                                NaN
        1498303230                                                NaN
        1511328799                         https://www.futterhaus.de/
        1608667951                                                NaN
        1643105094              http://www.marine-aquarium-senior.net
        1774557661                                                NaN
        1779217862  https://www.fressnapf.de/stores/fressnapf-berl...

                                                         full_address  \
element id
node    111810614   Fressnapf, Lützenstraße, Halensee, Charlottenb...
        346138343   Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...
        417360251   Fressnapf, 128b, Storkower Straße, Blumenviert...
        438385039   Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...
        446899194   Das Futterhaus, 52, Lahnstraße, Richardkiez, N...
        701825313   Natürlich Hund, 57, Nassauische Straße, Güntze...
        800755193   Hundesalon, 45-46, Alt-Reinickendorf, Reinicke...
        861870108   Fressnapf, 23-27, Quedlinburger Straße, Heller...
        1112653257  Fressnapf, Ludwigsfelder Straße, Zehlendorf, S...
        1157588586  Das Futterhaus, Pankower Allee, Große Lettekol...
        1198087358  Fressnapf, 26, Klosterstraße, Georg-Ramin-Sied...
        1311479655  Zoo fridolin, 81, Kaiserin-Augusta-Allee, Kalo...
        1427998890  Fressnapf, Am Zeppelinpark, Siedlung Neu-Jerus...
        1457600608  Fressnapf, 47, Pankower Allee, Große Lettekolo...
        1498303230  Das Futterhaus, 108, Weißenhöher Straße, Alt-B...
        1511328799  Das Futterhaus, 10, Hermannplatz, Reuterkiez, ...
        1608667951  Fressnapf, 68, Stresemannstraße, Zeitungsviert...
        1643105094  Marine Aquarium Senior, 85-86, Oranienburger S...
        1774557661  Steffis Futterkeks, 63, Cranachstraße, Malervi...
        1779217862  Fressnapf, 32, Volkradstraße, Sewanviertel, Fr...

                    longitude   latitude
element id
node    111810614   13.288411  52.499735
        346138343   13.367520  52.542519
        417360251   13.451963  52.533614
        438385039   13.308440  52.478876
        446899194   13.448016  52.468671
        701825313   13.326709  52.490786
        800755193   13.353503  52.574597
        861870108   13.610827  52.540182
        1112653257  13.242376  52.423217
        1157588586  13.366604  52.564244
        1198087358  13.196675  52.530161
        1311479655  13.306466  52.525533
        1427998890  13.128834  52.528430
        1457600608  13.370716  52.564726
        1498303230  13.559790  52.506351
        1511328799  13.424396  52.487895
        1608667951  13.384378  52.503123
        1643105094  13.333377  52.595326
        1774557661  13.342218  52.468926
        1779217862  13.507241  52.499245

Using petstores_cleaned.head(20) I preview the first 20 rows of the cleaned dataset.  

This helps me visually confirm that:  
* The selected columns are correct  
* The full_address column was created properly  
* Latitude and longitude values look valid  
* The data structure matches the expected format

In [ ]:
print("Final dataset shape:", petstores_cleaned.shape)
print("Columns:", list(petstores_cleaned.columns))
print("Any missing values left?", petstores_cleaned.isna().any().sum())

Final dataset shape: (82, 10)
Columns: ['geometry', 'district_id', 'name', 'brand', 'opening_hours', 'phone', 'website', 'full_address', 'longitude', 'latitude']
Any missing values left? 4

In [ ]:
petstores_cleaned.isna().sum()

geometry          0
district_id       0
name              0
brand            44
opening_hours    17
phone            65
website          58
full_address      0
longitude         0
latitude          0
dtype: int64

In [ ]:
petstores_gdf.head()

                                    geometry           brand brand:wikidata  \
element id
node    111810614  POINT (13.28841 52.49974)       Fressnapf        Q875796
        346138343  POINT (13.36752 52.54252)       Fressnapf        Q875796
        417360251  POINT (13.45196 52.53361)       Fressnapf        Q875796
        438385039  POINT (13.30844 52.47888)             NaN            NaN
        446899194  POINT (13.44802 52.46867)  Das Futterhaus       Q1167914

                     brand:wikipedia  check_date check_date:opening_hours  \
element id
node    111810614       en:Fressnapf  2025-10-29               2025-10-29
        346138343       de:Fressnapf  2025-08-28               2025-08-28
        417360251       en:Fressnapf         NaN                      NaN
        438385039                NaN         NaN                      NaN
        446899194  de:Das Futterhaus         NaN                      NaN

                             name                      opening_hours shop  \
element id
node    111810614       Fressnapf  Mo-Fr 09:00-20:00; Sa 09:00-19:00  pet
        346138343       Fressnapf  Mo-Fr 09:00-20:00; Sa 09:00-18:00  pet
        417360251       Fressnapf                                NaN  pet
        438385039  Lucas Tierwelt                  Mo-Sa 08:00-20:00  pet
        446899194  Das Futterhaus                                NaN  pet

                  addr:housenumber        addr:street level wheelchair  \
element id
node    111810614              NaN                NaN   NaN        NaN
        346138343            10-11       Müllerstraße     0        yes
        417360251             128b   Storkower Straße   NaN    limited
        438385039               95  Forckenbeckstraße   NaN        NaN
        446899194              NaN                NaN   NaN        NaN

                  addr:city addr:country addr:postcode      addr:suburb  \
element id
node    111810614       NaN          NaN           NaN              NaN
        346138343       NaN          NaN           NaN              NaN
        417360251    Berlin           DE         10407  Prenzlauer Berg
        438385039    Berlin           DE         14199    Schmargendorf
        446899194       NaN          NaN           NaN              NaN

                  toilets:wheelchair  \
element id
node    111810614                NaN
        346138343                NaN
        417360251                 no
        438385039                NaN
        446899194                NaN

                                              wheelchair:description  \
element id
node    111810614                                                NaN
        346138343                                                NaN
        417360251  Behindertenparkplätze werden dauerhaft als Abs...
        438385039                                                NaN
        446899194                                                NaN

                                          website  pet phone email  \
element id
node    111810614                             NaN  NaN   NaN   NaN
        346138343                             NaN  NaN   NaN   NaN
        417360251                             NaN  NaN   NaN   NaN
        438385039  https://www.lucas-tierwelt.de/  NaN   NaN   NaN
        446899194                             NaN  NaN   NaN   NaN

                  payment:american_express payment:coins payment:mastercard  \
element id
node    111810614                      NaN           NaN                NaN
        346138343                      NaN           NaN                NaN
        417360251                      NaN           NaN                NaN
        438385039                      NaN           NaN                NaN
        446899194                      NaN           NaN                NaN

                  payment:notes payment:visa contact:email contact:fax  \
element id
node    111810614           NaN          NaN           NaN         NaN
        346138343           NaN          NaN           NaN         NaN
        417360251           NaN          NaN           NaN         NaN
        438385039           NaN          NaN           NaN         NaN
        446899194           NaN          NaN           NaN         NaN

                  contact:phone contact:website note operator  fax  \
element id
node    111810614           NaN             NaN  NaN      NaN  NaN
        346138343           NaN             NaN  NaN      NaN  NaN
        417360251           NaN             NaN  NaN      NaN  NaN
        438385039           NaN             NaN  NaN      NaN  NaN
        446899194           NaN             NaN  NaN      NaN  NaN

                  payment:credit_cards payment:debit_cards post_office  \
element id
node    111810614                  NaN                 NaN         NaN
        346138343                  NaN                 NaN         NaN
        417360251                  NaN                 NaN         NaN
        438385039                  NaN                 NaN         NaN
        446899194                  NaN                 NaN         NaN

                  post_office:brand post_office:brand:wikidata  \
element id
node    111810614               NaN                        NaN
        346138343               NaN                        NaN
        417360251               NaN                        NaN
        438385039               NaN                        NaN
        446899194               NaN                        NaN

                  payment:girocard source contact:facebook delivery  \
element id
node    111810614              NaN    NaN              NaN      NaN
        346138343              NaN    NaN              NaN      NaN
        417360251              NaN    NaN              NaN      NaN
        438385039              NaN    NaN              NaN      NaN
        446899194              NaN    NaN              NaN      NaN

                  description species:de addr:inclusion contact:instagram  \
element id
node    111810614         NaN        NaN            NaN               NaN
        346138343         NaN        NaN            NaN               NaN
        417360251         NaN        NaN            NaN               NaN
        438385039         NaN        NaN            NaN               NaN
        446899194         NaN        NaN            NaN               NaN

                  ref:vatin dispensing opening_hours:covid19 old_name  \
element id
node    111810614       NaN        NaN                   NaN      NaN
        346138343       NaN        NaN                   NaN      NaN
        417360251       NaN        NaN                   NaN      NaN
        438385039       NaN        NaN                   NaN      NaN
        446899194       NaN        NaN                   NaN      NaN

                  wikimedia_commons surveillance start_date  \
element id
node    111810614               NaN          NaN        NaN
        346138343               NaN          NaN        NaN
        417360251               NaN          NaN        NaN
        438385039               NaN          NaN        NaN
        446899194               NaN          NaN        NaN

                  opening_hours:signed organic post_office:ref  \
element id
node    111810614                  NaN     NaN             NaN
        346138343                  NaN     NaN             NaN
        417360251                  NaN     NaN             NaN
        438385039                  NaN     NaN             NaN
        446899194                  NaN     NaN             NaN

                  post_office:type  url alt_name building roof:shape  \
element id
node    111810614              NaN  NaN      NaN      NaN        NaN
        346138343              NaN  NaN      NaN      NaN        NaN
        417360251              NaN  NaN      NaN      NaN        NaN
        438385039              NaN  NaN      NaN      NaN        NaN
        446899194              NaN  NaN      NaN      NaN        NaN

                  building:colour building:levels payment:cash roof:levels  \
element id
node    111810614             NaN             NaN          NaN         NaN
        346138343             NaN             NaN          NaN         NaN
        417360251             NaN             NaN          NaN         NaN
        438385039             NaN             NaN          NaN         NaN
        446899194             NaN             NaN          NaN         NaN

                  indoor room entrance  index_right  \
element id
node    111810614    NaN  NaN      NaN           27
        346138343    NaN  NaN      NaN            4
        417360251    NaN  NaN      NaN            8
        438385039    NaN  NaN      NaN           23
        446899194    NaN  NaN      NaN           50

                                     district     neighborhood district_id  \
element id
node    111810614  Charlottenburg-Wilmersdorf         Halensee    11004004
        346138343                       Mitte          Wedding    11001001
        417360251                      Pankow  Prenzlauer Berg    11003003
        438385039  Charlottenburg-Wilmersdorf    Schmargendorf    11004004
        446899194                    Neukölln         Neukölln    11008008

                   longitude   latitude  \
element id
node    111810614  13.288411  52.499735
        346138343  13.367520  52.542519
        417360251  13.451963  52.533614
        438385039  13.308440  52.478876
        446899194  13.448016  52.468671

                                                        full_address
element id
node    111810614  Fressnapf, Lützenstraße, Halensee, Charlottenb...
        346138343  Fressnapf, 10-11, Müllerstraße, Sprengelkiez, ...
        417360251  Fressnapf, 128b, Storkower Straße, Blumenviert...
        438385039  Lucas Tierwelt, 95, Forckenbeckstraße, Schmarg...
        446899194  Das Futterhaus, 52, Lahnstraße, Richardkiez, N...

In [ ]:
petstores_cleaned.to_csv("berlin_pet_stores_cleaned.csv", index=False)

In [ ]:
petstores_final = petstores_final.loc[:, ~petstores_final.columns.duplicated()]

In [ ]:
petstores_final[['district_id', 'neighborhood']].head()

   district_id     neighborhood
0     11004004         Halensee
1     11001001          Wedding
2     11003003  Prenzlauer Berg
3     11004004    Schmargendorf
4     11008008         Neukölln

In [ ]:
petstores_final[['district_id', 'neighborhood']].isna().sum()

district_id     0
neighborhood    0
dtype: int64

Here, I check whether the district_id and neighborhood columns contain any missing values. The result shows 0 missing entries, confirming that the spatial mapping worked correctly and all records have valid locations.

In [ ]:
petstores_final.columns

Index(['district_id', 'name', 'brand', 'opening_hours', 'phone', 'website',
       'full_address', 'longitude', 'latitude', 'district', 'neighborhood'],
      dtype='object')

Here, I check the column names of my final dataset to make sure they match the expected schema. All columns appear correctly named and aligned with the structure I used throughout the transformation.

In [ ]:
%%sql postgresql+psycopg://nuran_nalci:LSGPrTr27Rllc3TT40iq@localhost:5433/layereddb

CREATE TABLE IF NOT EXISTS test_pet_stores (
    district_id VARCHAR(20),
    name VARCHAR(200)
);

Done.

[]

Here, I create a small test table called test_pet_stores.
I use it only to verify that the insert operation works correctly in this environment. This table is not part of the final data model — it’s just for testing purposes.

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg://nuran_nalci:LSGPrTr27Rllc3TT40iq@localhost:5433/layereddb")

In [ ]:
petstores_final.to_sql(
    "pet_stores",
    engine,
    if_exists="replace",
    index=False
)

-1

In this cell, I load my final dataset into the pet_stores table.
By using if_exists="replace", I completely overwrite the old table and recreate it with the cleaned dataset of 82 rows, ensuring that no outdated or duplicated records remain.

In [ ]:
import pandas as pd

pd.read_sql("SELECT COUNT(*) FROM pet_stores;", engine)

   count
0     82

Here, I check how many rows were successfully loaded into the pet_stores table.

In [ ]:
petstores_final.duplicated().sum()

np.int64(0)

I checked the dataset for duplicate rows to ensure that no repeated entries remain in the final table. The result shows 0 duplicates, meaning the dataset is fully unique and clean.

In [ ]:
petstores_final['district_id'].isna().sum()
petstores_final['neighborhood'].isna().sum()

np.int64(0)

I verified that there are no missing values in the district_id and neighborhood columns. Both columns return zero missing values, confirming that spatial mapping was successfully completed without gaps.

In [ ]:
petstores_final[(petstores_final.latitude < 52.3) | (petstores_final.latitude > 52.7)]

Empty DataFrame
Columns: [district_id, name, brand, opening_hours, phone, website, full_address, longitude, latitude, district, neighborhood]
Index: []

I checked whether all latitude and longitude values are inside Berlin’s official boundaries. I used Berlin’s bounding box values from OSM (OpenStreetMap). All rows returned an empty result, so all coordinates are within Berlin. No out-of-bound locations were found.

Foreign Key Validation Note:
The foreign key check returned False because the districts reference table is not available on the current test database. The data itself is correct, and all district_id values match the cleaned dataset. This check will succeed once the reference table is present in the environment.

This check compares district_id values against the reference list. Since the districts table is missing in the test environment, the list is empty and all rows appear “invalid”. Once the reference table is added, this validation will produce the correct result.

In [ ]:
petstores_final.shape

(82, 11)

This cell confirms the total number of rows and columns in the final dataset. After all cleaning and transformation steps, the expected result is 82 rows and 11 columns.

In [ ]:
petstores_final.dtypes
petstores_final.columns

Index(['district_id', 'name', 'brand', 'opening_hours', 'phone', 'website',
       'full_address', 'longitude', 'latitude', 'district', 'neighborhood'],
      dtype='object')

I checked the final dataset’s column names and data types to ensure consistency with the expected schema.
All columns appear correctly named and follow consistent types (strings and numeric values).
No unexpected or missing columns were found.

Step 2 : 
Data Cleaning & Standardization Notes

Steps I Followed During Data Cleaning

* I first loaded the raw OSM data into a GeoDataFrame called petstores_gdf.

* I reviewed the full list of available columns to understand what information the dataset contained.

* I used isna().sum() to check the amount of missing data in each column.

* Columns that were mostly empty or not relevant to the project were removed.

* I selected a meaningful subset of columns and created a cleaned dataset: petstores_cleaned.

Standardizing Columns

* Address fields (addr:street, addr:housenumber, addr:postcode, addr:city) were combined into a single, readable full_address column.

* To work with geographic data more easily, I extracted latitude and longitude from the geometry column.

* The original, now redundant address columns were removed.

Data Sources and Integration

* At this stage, only OSM was used as the primary data source.

 Challenges I Faced

* The most challenging part for me was deciding which columns were actually useful.
The raw OSM dataset contains many fields, and the column names are not always intuitive.
So I needed time to understand what each field represented.

* Using isna().sum() to examine missing data helped me see which columns had meaningful values and which were mostly empty.
This made the column selection process much clearer.

* I also needed to pay attention when creating the full_address column because some rows were missing one or more address components.
To handle this, I used fillna(''), which allowed me to merge the address parts cleanly without errors.

* Overall, once I understood the structure of the data, the workflow became more natural and easier to follow.


Deciding Which Data to Keep

 I kept these columns because they provide direct value to the user and to the application:

* name — Important for identifying the store

* geometry — Contains the raw geographic location data

* brand — Needed for segmenting and categorizing stores by brand

* full_address — Provides a clean and readable address format

* opening_hours — Useful for user decision-making

* phone, website — Helps with direct communication

* latitude, longitude — Necessary for map display and spatial analysis

 Columns removed — because they were too incomplete or not relevant:

* Payment-related fields (payment:*)

* OSM metadata (source, wikidata)

Step 3 Summary — Data Cleaning, Transformation & Validation
1. Cleaning & Standardization Steps

In this step, I cleaned and standardized the raw OSM pet store data to prepare it for integration into the Berlin Data Platform.
Here are the key steps I followed:

Loaded raw OSM pet store data into a GeoDataFrame.

Inspected all columns to understand available attributes and removed fields that were irrelevant to the project.

Used .isna().sum() to check missing values column by column.

Standardized column names and selected only the fields necessary for the final schema.

Converted longitude/latitude into geometry points using shapely.geometry.Point.

Ensured consistent string formatting and corrected minor text inconsistencies.

2. Transformation & Spatial Mapping

To attach each pet store to its administrative boundaries:

Loaded district and neighborhood boundaries from GeoJSON.

Performed two spatial joins:

petstores_gdf -> districts (mapping district_id + district)

petstores_with_districts -> neighborhoods (mapping neighborhood)

Removed temporary geometry/index columns created during the join process.

Renamed columns to match the final schema (e.g., district_id_left -> district_id).

Verified all coordinates were within Berlin using bounding-box filters.

3. Validation & Quality Checks

I performed several quality checks to make sure the dataset is consistent and ready for integration:

Duplicate Check:
Verified that the final dataset contains no duplicate rows.

Missing Value Check:
Confirmed that district_id and neighborhood fields have no missing values after spatial joins.

Coordinate Validation:
Ensured all latitude and longitude values fall within Berlin’s correct geographic boundaries.

Foreign Key Logic Check:
Compared district_id values against the districts reference table (local environment).
Missing reference table caused the check to return False, but all district_id values match the cleaned dataset.

Schema Consistency:
Verified final column names, data types, and dataset shape (82 rows x 11 columns).

4. Assumptions & Data Issues

During cleaning and mapping, I made a few assumptions:

Some OSM entries had incomplete address or phone information; these were kept as NULL rather than removed.

Coordinates from OSM are assumed accurate enough for spatial joining.

District reference table is not available in the current local DB -> validation was performed logically within the notebook.

Store IDs were not provided by the source; therefore, no primary key was generated.

5. Reference Design Justification

Using district_id as a foreign key ensures proper linkage to Berlin administrative layers.

Keeping district and neighborhood as descriptive fields improves readability for analytics and frontend usage.

Removing geometry columns gives a clean relational table suitable for database storage.

Spatial joins are used to ensure correct administrative alignment regardless of input source inconsistencies.

6. Spatial Mapping Methods Used

I used the following geospatial operations:

geopandas.sjoin(..., predicate="within")
for geometric containment mapping.

shapely.geometry.Point()
to construct geometry objects from longitude/latitude pairs.

Source geometries used:

districts_enhanced.geojson

neighborhoods_enhanced.geojson

I used OSMnx to retrieve geographic coordinates and structural metadata from OpenStreetMap.Here are the references related to the spatial data source and OSMnx:

OSMnx Documentation:
*  https://osmnx.readthedocs.io/en/stable/

OSMnx GitHub Repository:
*  https://github.com/gboeing/osmnx

OpenStreetMap (OSM) Data Source: 
*  https://www.openstreetmap.org/

GitHub references:
*  https://github.com/webeet-io/layered-populate-data-pool-da/tree/main/mapping
*  https://github.com/webeet-io/layered-populate-data-pool-da/wiki/Layered-DB-:-Berlin-Data-Source-table-info#districts

In [ ]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [ ]:
%sql SELECT 1;

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/sql/magic.py", line 196, in execute
    conn = sql.connection.Connection.set(
        connect_str,
    ...<2 lines>...
        creator=args.creator,
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/sql/connection.py", line 82, in set
    raise ConnectionError(
        "Environment variable $DATABASE_URL not set, and no connect string given."
    )
sql.connection.ConnectionError: Environment variable $DATABASE_URL not set, and no connect string given.

Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])

In [ ]:
import sys
!{sys.executable} -m pip install geopy
!{sys.executable} -m pip install ipython-sql
!{sys.executable} -m pip install "psycopg[binary]"
!{sys.executable} -m pip install sqlalchemy

Requirement already satisfied: geopy in /opt/anaconda3/lib/python3.13/site-packages (2.4.1)
Requirement already satisfied: geographiclib<3,>=1.52 in /opt/anaconda3/lib/python3.13/site-packages (from geopy) (2.1)
Requirement already satisfied: ipython-sql in /opt/anaconda3/lib/python3.13/site-packages (0.5.0)
Requirement already satisfied: prettytable in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (3.17.0)
Requirement already satisfied: ipython in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (8.30.0)
Requirement already satisfied: sqlalchemy>=2.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (2.0.39)
Requirement already satisfied: sqlparse in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (0.5.3)
Requirement already satisfied: six in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (1.17.0)
Requirement already satisfied: ipython-genutils in /opt/anaconda3/lib/python3.13/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy>=2.0->ipython-sql) (4.12.2)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.19.2)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (2.19.1)
Requirement already satisfied: stack-data in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (5.14.3)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/lib/python3.13/site-packages (from ipython->ipython-sql) (4.8.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.13/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->ipython-sql) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /opt/anaconda3/lib/python3.13/site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.13/site-packages (from pexpect>4.3->ipython->ipython-sql) (0.7.0)
Requirement already satisfied: executing in /opt/anaconda3/lib/python3.13/site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in /opt/anaconda3/lib/python3.13/site-packages (from stack-data->ipython->ipython-sql) (3.0.0)
Requirement already satisfied: pure-eval in /opt/anaconda3/lib/python3.13/site-packages (from stack-data->ipython->ipython-sql) (0.2.2)
Requirement already satisfied: psycopg[binary] in /opt/anaconda3/lib/python3.13/site-packages (3.2.12)
Requirement already satisfied: psycopg-binary==3.2.12 in /opt/anaconda3/lib/python3.13/site-packages (from psycopg[binary]) (3.2.12)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.39)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.12.2)