**📍 Fetch data about coworking-spaces in Berlin from OpenStreetMap (OSM)**

In [120]:
#%pip install osmnx geopandas pandas
#%pip install geopy

In [121]:
import osmnx as ox
import geopandas as gpd
import geopy
import pandas as pd

In [122]:
tags = {"office": "coworking"}

ox.settings.use_cache = True
ox.settings.log_console = True

gdf = ox.features.features_from_place("Berlin, Germany", tags=tags)

print(f"Number of coworking-spaces entries fetched: {len(gdf)}")

Number of coworking-spaces entries fetched: 100

In [123]:
# filter columns that relevant to project
columns = [
    "name","addr:street","addr:housenumber","addr:postcode",
    "addr:city","addr:country","addr:suburb","opening_hours",
    "internet_access","wheelchair","contact:phone",
    "contact:email","contact:website","geometry"
]
gdf_coworking_spaces = gdf[[col for col in columns if col in gdf.columns]].copy()

In [124]:
# Extract Latitude and Longitude
gdf_coworking_spaces['geometry'] = gdf_coworking_spaces['geometry'].apply(lambda geom: geom if geom.geom_type == 'Point' else geom.representative_point())

gdf_coworking_spaces["latitude"] = gdf.geometry.centroid.y
gdf_coworking_spaces["longitude"] = gdf.geometry.centroid.x

/var/folders/tg/38ly2d5x39d3gfjppq_39pcc0000gn/T/ipykernel_67971/1022450415.py:4: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf_coworking_spaces["latitude"] = gdf.geometry.centroid.y
/var/folders/tg/38ly2d5x39d3gfjppq_39pcc0000gn/T/ipykernel_67971/1022450415.py:5: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf_coworking_spaces["longitude"] = gdf.geometry.centroid.x

In [125]:
# cleaning columnnames for better understanding
gdf_coworking_spaces = gdf_coworking_spaces.rename(
    columns=lambda c: c.replace("addr:", "").replace("contact:", "")
)

In [126]:
missing_count = gdf_coworking_spaces.isna().sum().sort_values(ascending=False)

row_count = len(gdf_coworking_spaces)
print(row_count)
missing = pd.DataFrame({
    "missing_count": missing_count,
    "missing_pct": (missing_count / row_count * 100).round(1)
}).sort_values(by="missing_pct", ascending=False)

print(missing)

100
                 missing_count  missing_pct
phone                       88         88.0
email                       88         88.0
wheelchair                  79         79.0
website                     78         78.0
internet_access             73         73.0
opening_hours               69         69.0
suburb                      50         50.0
country                     49         49.0
city                        22         22.0
postcode                    20         20.0
street                      14         14.0
housenumber                 13         13.0
name                         3          3.0
geometry                     0          0.0
latitude                     0          0.0
longitude                    0          0.0

In [127]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import numpy as np
import pandas as pd

# Geocoder starten
geolocator = Nominatim(user_agent="coworking_reverse_geocoder")
reverse = RateLimiter(geolocator.reverse, min_delay_seconds=1)

# Mapping: Nominatim → Deine Spaltennamen
mapping = {
    "road": "street",
    "house_number": "housenumber",
    "postcode": "postcode",
    "city": "city",
    "suburb": "suburb"
}

def reverse_geocode(lat, lon):
    try:
        location = reverse((lat, lon), language="de")
        if location is None:
            return {}
        return location.raw.get("address", {})
    except:
        return {}

# Durch alle Zeilen iterieren
for idx, row in gdf_coworking_spaces.iterrows():
    
    # Prüfen, ob überhaupt ein Feld fehlt
    needs_geocoding = any(
        field not in row or row[field] in ["unknown", None, ""] or pd.isna(row[field])
        for field in mapping.values()
    )
    
    if not needs_geocoding:
        continue  # alles vorhanden → überspringen
    
    lat, lon = row["latitude"], row["longitude"]
    address = reverse_geocode(lat, lon)
    
    # Werte eintragen
    for osm_key, df_key in mapping.items():
        
        # Nur eintragen, wenn bisher leer
        if df_key not in row or row[df_key] in ["unknown", None, ""] or pd.isna(row[df_key]):
            value = address.get(osm_key, "")
            gdf_coworking_spaces.at[idx, df_key] = value

RateLimiter caught an error, retrying (0/2 tries). Called with (*((52.5580996, 13.4147115),), **{'language': 'de'}).
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/opt/anaconda3/lib/python3.13/http/client.py", line 1430, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/opt/anaconda3/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/opt/anaconda3/lib/python3.13/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/anaconda3/lib/python3.13/ssl.py", line 1304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/ssl.py", line 1138, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
        self, url, f"Read timed out. (read timeout={timeout_value})"
    ) from err
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=52.5580996&lon=13.4147115&format=json&accept-language=de&addressdetails=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=52.5580996&lon=13.4147115&format=json&accept-language=de&addressdetails=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/geocoders/nominatim.py", line 372, in reverse
    return self._call_geocoder(url, callback, timeout=timeout)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=52.5580996&lon=13.4147115&format=json&accept-language=de&addressdetails=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (0/2 tries). Called with (*((52.512511382822474, 13.423889145179139),), **{'language': 'de'}).
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 534, in _make_request
    response = conn.getresponse()
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connection.py", line 516, in getresponse
    httplib_response = super().getresponse()
  File "/opt/anaconda3/lib/python3.13/http/client.py", line 1430, in getresponse
    response.begin()
    ~~~~~~~~~~~~~~^^
  File "/opt/anaconda3/lib/python3.13/http/client.py", line 331, in begin
    version, status, reason = self._read_status()
                              ~~~~~~~~~~~~~~~~~^^
  File "/opt/anaconda3/lib/python3.13/http/client.py", line 292, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/socket.py", line 719, in readinto
    return self._sock.recv_into(b)
           ~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/anaconda3/lib/python3.13/ssl.py", line 1304, in recv_into
    return self.read(nbytes, buffer)
           ~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/ssl.py", line 1138, in read
    return self._sslobj.read(len, buffer)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
        conn,
    ...<10 lines>...
        **response_kw,
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
        self, url, f"Read timed out. (read timeout={timeout_value})"
    ) from err
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
        method=request.method,
    ...<9 lines>...
        chunked=chunked,
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 871, in urlopen
    return self.urlopen(
           ~~~~~~~~~~~~^
        method,
        ^^^^^^^
    ...<13 lines>...
        **response_kw,
        ^^^^^^^^^^^^^^
    )
    ^
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
        method, url, error=new_e, _pool=self, _stacktrace=sys.exc_info()[2]
    )
  File "/opt/anaconda3/lib/python3.13/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=52.512511382822474&lon=13.423889145179139&format=json&accept-language=de&addressdetails=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=52.512511382822474&lon=13.423889145179139&format=json&accept-language=de&addressdetails=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
    ^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/geocoders/nominatim.py", line 372, in reverse
    return self._call_geocoder(url, callback, timeout=timeout)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/opt/anaconda3/lib/python3.13/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /reverse?lat=52.512511382822474&lon=13.423889145179139&format=json&accept-language=de&addressdetails=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

In [128]:
missing_count = gdf_coworking_spaces.isna().sum().sort_values(ascending=False)

row_count = len(gdf_coworking_spaces)
print(row_count)
missing = pd.DataFrame({
    "missing_count": missing_count,
    "missing_pct": (missing_count / row_count * 100).round(1)
}).sort_values(by="missing_pct", ascending=False)

print(missing)

100
                 missing_count  missing_pct
phone                       88         88.0
email                       88         88.0
wheelchair                  79         79.0
website                     78         78.0
internet_access             73         73.0
opening_hours               69         69.0
country                     49         49.0
name                         3          3.0
street                       0          0.0
housenumber                  0          0.0
postcode                     0          0.0
city                         0          0.0
suburb                       0          0.0
geometry                     0          0.0
latitude                     0          0.0
longitude                    0          0.0

In [129]:
gdf_coworking_spaces = gdf_coworking_spaces.fillna("unknown")

In [130]:
missing_count = gdf_coworking_spaces.isna().sum().sort_values(ascending=False)

row_count = len(gdf_coworking_spaces)
print(row_count)
missing = pd.DataFrame({
    "missing_count": missing_count,
    "missing_pct": (missing_count / row_count * 100).round(1)
}).sort_values(by="missing_pct", ascending=False)

print(missing)

100
                 missing_count  missing_pct
name                         0          0.0
street                       0          0.0
housenumber                  0          0.0
postcode                     0          0.0
city                         0          0.0
country                      0          0.0
suburb                       0          0.0
opening_hours                0          0.0
internet_access              0          0.0
wheelchair                   0          0.0
phone                        0          0.0
email                        0          0.0
website                      0          0.0
geometry                     0          0.0
latitude                     0          0.0
longitude                    0          0.0

In [131]:
gdf_coworking_spaces

                                         name               street  \
element id
node    330264334                St. Oberholz   Rosenthaler Straße
        459659033                     unknown      Ella-Kay-Straße
        1776155022  Pulsraum Coworking Berlin      Kottbusser Damm
        1827346141                       Fora     Unter den Linden
        2181178532           Hauptstadt Räume           Kochstraße
...                                       ...                  ...
way     262752250                     HAUS  1       Oberlandstraße
        293386119         Coworking Holzmarkt
        389457705                     unknown    Scharnweberstraße
        389457733                    werkhain    Frankfurter Allee
        679549771                      B-Part  Luckenwalder Straße

                   housenumber postcode    city  country           suburb  \
element id
node    330264334           72    10119  Berlin       DE            Mitte
        459659033           38    10405  Berlin  unknown  Prenzlauer Berg
        1776155022          25    10967  Berlin       DE        Kreuzberg
        1827346141          40    10117  Berlin       DE            Mitte
        2181178532                10969  Berlin  unknown        Kreuzberg
...                        ...      ...     ...      ...              ...
way     262752250        25-36    12099  Berlin  unknown        Tempelhof
        293386119           43    10243  Berlin       DE   Friedrichshain
        389457705                 10247  Berlin  unknown   Friedrichshain
        389457733          108    10247  Berlin  unknown   Friedrichshain
        679549771           6b    10963  Berlin       DE        Kreuzberg

                                                        opening_hours  \
element id
node    330264334   Mo-Th 08:00-24:00, Fr 08:00-03:00, Sa 09:00-03...
        459659033                                             unknown
        1776155022                  Mo-Fr 07:00-21:00; Sa 10:00-19:00
        1827346141                                            unknown
        2181178532                                            unknown
...                                                               ...
way     262752250                                             unknown
        293386119                                             unknown
        389457705                                             unknown
        389457733                                             unknown
        679549771                                   Mo-Fr 09:00-18:00

                   internet_access wheelchair            phone  \
element id
node    330264334             wlan    limited  +49 30 24085586
        459659033          unknown    unknown          unknown
        1776155022            wlan    unknown          unknown
        1827346141         unknown    unknown          unknown
        2181178532         unknown    unknown          unknown
...                            ...        ...              ...
way     262752250          unknown    unknown          unknown
        293386119             wlan    unknown          unknown
        389457705          unknown    unknown          unknown
        389457733          unknown    unknown          unknown
        679549771          unknown    unknown          unknown

                                    email  \
element id
node    330264334   info@sanktoberholz.de
        459659033                 unknown
        1776155022                unknown
        1827346141                unknown
        2181178532                unknown
...                                   ...
way     262752250                 unknown
        293386119                 unknown
        389457705                 unknown
        389457733                 unknown
        679549771                 unknown

                                                            website  \
element id
node    330264334   https://sanktoberholz.de/standorte/rosenthaler/
        459659033                                           unknown
        1776155022                                          unknown
        1827346141                                          unknown
        2181178532                                          unknown
...                                                             ...
way     262752250                                           unknown
        293386119                                           unknown
        389457705                                           unknown
        389457733                                           unknown
        679549771                                           unknown

                                     geometry   latitude  longitude
element id
node    330264334   POINT (13.40178 52.52953)  52.529530  13.401782
        459659033    POINT (13.4328 52.54017)  52.540165  13.432801
        1776155022  POINT (13.42387 52.48963)  52.489635  13.423870
        1827346141  POINT (13.38644 52.51716)  52.517159  13.386443
        2181178532  POINT (13.38708 52.50659)  52.506594  13.387084
...                                       ...        ...        ...
way     262752250   POINT (13.41075 52.46439)  52.464388  13.410747
        293386119   POINT (13.42389 52.51251)  52.512511  13.423889
        389457705    POINT (13.47474 52.5127)  52.512696  13.474740
        389457733   POINT (13.47476 52.51278)  52.512781  13.474764
        679549771   POINT (13.37338 52.49906)  52.499079  13.373378

[100 rows x 16 columns]

In [132]:
distinct = gdf_coworking_spaces.nunique().sort_values(ascending=False)
print(distinct)

geometry           100
latitude           100
longitude          100
street              91
name                83
housenumber         66
postcode            48
website             23
opening_hours       20
suburb              18
phone               13
email               12
wheelchair           4
internet_access      3
country              2
city                 1
dtype: int64

In [133]:
# Example: top 10 brands
print("\nTop 10 brands:")
print(gdf_coworking_spaces["name"].value_counts().head(10))

Top 10 brands:
name
WeWork                       8
Design Offices               5
unknown                      3
werkhain                     3
St. Oberholz                 2
tuesday coworking            2
Helix Hub                    1
& Co                         1
Coworking Toddler            1
b+ office Coworking Space    1
Name: count, dtype: int64

In [134]:
print("\nTop 10 brands:")
print(gdf_coworking_spaces["street"].value_counts().head(10))

Top 10 brands:
street
Frankfurter Allee         3
Rosenthaler Straße        2
Europaplatz               2
Wilhelmine-Gemberg-Weg    2
Oberlandstraße            2
Hauptstraße               2
Stresemannstraße          2
Unter den Linden          2
Stockholmer Straße        1
Max-Urich-Straße          1
Name: count, dtype: int64

In [135]:
print("\nTop 10 brands:")
print(gdf_coworking_spaces["opening_hours"].value_counts().head(10))

Top 10 brands:
opening_hours
unknown                                                              69
Mo-Fr 09:00-18:00                                                     6
24/7                                                                  4
Mo-Fr 08:30-18:00                                                     4
Mo-Fr 09:00-17:00                                                     2
Mo-Th 08:00-24:00, Fr 08:00-03:00, Sa 09:00-03:00, Su 09:00-24:00     1
Mo-Sa 10:00-22:00                                                     1
"nach Anwesenheit"                                                    1
Mo-Fr 08:30-18:30                                                     1
Mo-Fr 8:30-18:00                                                      1
Name: count, dtype: int64

In [136]:
print("\nTop 10 brands:")
print(gdf_coworking_spaces["postcode"].value_counts().head(10))

Top 10 brands:
postcode
10117    7
10247    4
10245    4
10179    4
10963    4
12099    4
10827    3
13347    3
10969    3
10785    3
Name: count, dtype: int64

In [137]:
print(gdf_coworking_spaces.geometry.geom_type.value_counts())

Point    100
Name: count, dtype: int64

In [138]:
print("Missing geometries:", gdf_coworking_spaces.geometry.isna().sum())

Missing geometries: 0

In [139]:
# Goal: Verify lat/lon look realistic.
# Why? If values are way off, something went wrong in conversion.

print("Latitude range:", gdf_coworking_spaces["latitude"].min(), "to", gdf_coworking_spaces["latitude"].max())

print("Longitude range:", gdf_coworking_spaces["longitude"].min(), "to", gdf_coworking_spaces["longitude"].max())

Latitude range: 52.4287643 to 52.5634242
Longitude range: 13.2975362 to 13.5285457

In [140]:
# Save as GeoJSON (keeps geometry) and CSV

raw_geojson_path = "/Users/ramzi.gossing/Webeet Project Folder/Webeet.io internship documentaion/layered-populate-data-pool-da/coworking_centers/sources_coworking_spaces/coworking_centers.geojson"
raw_csv_path = "/Users/ramzi.gossing/Webeet Project Folder/Webeet.io internship documentaion/layered-populate-data-pool-da/coworking_centers/sources_coworking_spaces/coworking_centers.csv"


gdf_coworking_spaces.to_file(raw_geojson_path, driver="GeoJSON")
gdf_coworking_spaces.drop(columns="geometry").to_csv(raw_csv_path, index=False)

print(f"Raw data saved to: {raw_geojson_path} and {raw_csv_path}")

Raw data saved to: /Users/ramzi.gossing/Webeet Project Folder/Webeet.io internship documentaion/layered-populate-data-pool-da/coworking_centers/sources_coworking_spaces/coworking_centers.geojson and /Users/ramzi.gossing/Webeet Project Folder/Webeet.io internship documentaion/layered-populate-data-pool-da/coworking_centers/sources_coworking_spaces/coworking_centers.csv

In [141]:
gdf_coworking_spaces.dtypes

name                 object
street               object
housenumber          object
postcode             object
city                 object
country              object
suburb               object
opening_hours        object
internet_access      object
wheelchair           object
phone                object
email                object
website              object
geometry           geometry
latitude            float64
longitude           float64
dtype: object

In [142]:
# Convert certain columns to correct type

# Convert columns to specific types
df_transformed = gdf_coworking_spaces.copy()

# String columns (ensure consistent text type)
string_columns = [
    "name","street","housenumber","postcode",
    "city","country","suburb","opening_hours",
    "internet_access","wheelchair","phone",
    "email","website"
]
df_transformed[string_columns] = df_transformed[string_columns].apply(lambda col: col.astype("string").str.strip().str.lower()) # ensure text type

# Preview the updated dtypes
print(df_transformed.dtypes)

name               string[python]
street             string[python]
housenumber        string[python]
postcode           string[python]
city               string[python]
country            string[python]
suburb             string[python]
opening_hours      string[python]
internet_access    string[python]
wheelchair         string[python]
phone              string[python]
email              string[python]
website            string[python]
geometry                 geometry
latitude                  float64
longitude                 float64
dtype: object

In [143]:
# Display all columns
pd.set_option('display.max_columns', None)

# Display the first 3 rows of the dataframe
df_transformed.head(3)

                                         name              street housenumber  \
element id
node    330264334                st. oberholz  rosenthaler straße          72
        459659033                     unknown     ella-kay-straße          38
        1776155022  pulsraum coworking berlin     kottbusser damm          25

                   postcode    city  country           suburb  \
element id
node    330264334     10119  berlin       de            mitte
        459659033     10405  berlin  unknown  prenzlauer berg
        1776155022    10967  berlin       de        kreuzberg

                                                        opening_hours  \
element id
node    330264334   mo-th 08:00-24:00, fr 08:00-03:00, sa 09:00-03...
        459659033                                             unknown
        1776155022                  mo-fr 07:00-21:00; sa 10:00-19:00

                   internet_access wheelchair            phone  \
element id
node    330264334             wlan    limited  +49 30 24085586
        459659033          unknown    unknown          unknown
        1776155022            wlan    unknown          unknown

                                    email  \
element id
node    330264334   info@sanktoberholz.de
        459659033                 unknown
        1776155022                unknown

                                                            website  \
element id
node    330264334   https://sanktoberholz.de/standorte/rosenthaler/
        459659033                                           unknown
        1776155022                                          unknown

                                     geometry   latitude  longitude
element id
node    330264334   POINT (13.40178 52.52953)  52.529530  13.401782
        459659033    POINT (13.4328 52.54017)  52.540165  13.432801
        1776155022  POINT (13.42387 52.48963)  52.489635  13.423870

In [144]:
df_transformed.sample(10, random_state=42)

                                                      name  \
element id
node    12320665016                      das arbeitszimmer
        7287756217                    l19 bürogemeinschaft
        10124884255                                   & co
        7137713853        multimediabüro bild-schrift-zahl
        6915842784                         unicorn village
        6562944448   unicorn workspaces checkpoint charlie
        5151420230                                  wework
        11668641554                              techspace
        4231573654                         haus des holzes
        330264334                             st. oberholz

                                 street housenumber postcode    city  country  \
element id
node    12320665016    westerlandstraße                13189  berlin  unknown
        7287756217      lychener straße          19    10437  berlin       de
        10124884255         hauptstraße         153    10827  berlin       de
        7137713853            weidenweg          51    10249  berlin  unknown
        6915842784        richardstraße       85/86    12043  berlin       de
        6562944448     markgrafenstraße       62/63    10969  berlin  unknown
        5151420230          kemperplatz           1    10785  berlin       de
        11668641554   köpenicker straße         40b    10179  berlin  unknown
        4231573654       chausseestraße          99    10115  berlin  unknown
        330264334    rosenthaler straße          72    10119  berlin       de

                              suburb  \
element id
node    12320665016           pankow
        7287756217   prenzlauer berg
        10124884255       schöneberg
        7137713853    friedrichshain
        6915842784          neukölln
        6562944448         kreuzberg
        5151420230        tiergarten
        11668641554            mitte
        4231573654             mitte
        330264334              mitte

                                                         opening_hours  \
element id
node    12320665016                                            unknown
        7287756217                                             unknown
        10124884255                                            unknown
        7137713853                                             unknown
        6915842784                                             unknown
        6562944448                                             unknown
        5151420230                                             unknown
        11668641554                                            unknown
        4231573654                                             unknown
        330264334    mo-th 08:00-24:00, fr 08:00-03:00, sa 09:00-03...

                    internet_access wheelchair            phone  \
element id
node    12320665016         unknown    unknown          unknown
        7287756217          unknown    limited          unknown
        10124884255         unknown    unknown          unknown
        7137713853              yes    unknown          unknown
        6915842784          unknown    unknown          unknown
        6562944448          unknown    unknown          unknown
        5151420230          unknown    unknown          unknown
        11668641554         unknown    unknown          unknown
        4231573654          unknown    unknown          unknown
        330264334              wlan    limited  +49 30 24085586

                                     email  \
element id
node    12320665016                unknown
        7287756217                 unknown
        10124884255                unknown
        7137713853                 unknown
        6915842784                 unknown
        6562944448                 unknown
        5151420230                 unknown
        11668641554                unknown
        4231573654                 unknown
        330264334    info@sanktoberholz.de

                                                             website  \
element id
node    12320665016                                          unknown
        7287756217                                           unknown
        10124884255                                          unknown
        7137713853                                           unknown
        6915842784                                           unknown
        6562944448                                           unknown
        5151420230                                           unknown
        11668641554                                          unknown
        4231573654                                           unknown
        330264334    https://sanktoberholz.de/standorte/rosenthaler/

                                      geometry   latitude  longitude
element id
node    12320665016   POINT (13.41471 52.5581)  52.558100  13.414711
        7287756217    POINT (13.4156 52.54218)  52.542179  13.415602
        10124884255  POINT (13.35895 52.48858)  52.488581  13.358946
        7137713853   POINT (13.45226 52.51857)  52.518572  13.452259
        6915842784   POINT (13.44373 52.47593)  52.475929  13.443732
        6562944448   POINT (13.39398 52.50768)  52.507682  13.393984
        5151420230   POINT (13.37182 52.51084)  52.510839  13.371820
        11668641554   POINT (13.4255 52.50919)  52.509193  13.425504
        4231573654   POINT (13.38019 52.53258)  52.532584  13.380187
        330264334    POINT (13.40178 52.52953)  52.529530  13.401782

In [145]:
# Reset index to move 'element' and 'id' into columns
df_transformed = df_transformed.reset_index()

# Drop the 'element' column and rename 'id' to 'store_id'
df_transformed = df_transformed.drop(columns=["element"]).rename(columns={"id": "coworking_center_id"})
df_transformed["coworking_center_id"] = df_transformed["coworking_center_id"].astype("string")

In [146]:
df_transformed.sample(5, random_state=42)

,coworking_center_id,name,street,housenumber,postcode,city,country,suburb,opening_hours,internet_access,wheelchair,phone,email,website,geometry,latitude,longitude
83,12320665016,das arbeitszimmer,westerlandstraße,,13189,berlin,unknown,pankow,unknown,unknown,unknown,unknown,unknown,unknown,POINT (13.41471 52.5581),52.558100,13.414711
53,7287756217,l19 bürogemeinschaft,lychener straße,19,10437,berlin,de,prenzlauer berg,unknown,unknown,limited,unknown,unknown,unknown,POINT (13.4156 52.54218),52.542179,13.415602
70,10124884255,& co,hauptstraße,153,10827,berlin,de,schöneberg,unknown,unknown,unknown,unknown,unknown,unknown,POINT (13.35895 52.48858),52.488581,13.358946
45,7137713853,multimediabüro bild-schrift-zahl,weidenweg,51,10249,berlin,unknown,friedrichshain,unknown,yes,unknown,unknown,unknown,unknown,POINT (13.45226 52.51857),52.518572,13.452259
44,6915842784,unicorn village,richardstraße,85/86,12043,berlin,de,neukölln,unknown,unknown,unknown,unknown,unknown,unknown,POINT (13.44373 52.47593),52.475929,13.443732

In [147]:
df_transformed.head(2)

,coworking_center_id,name,street,housenumber,postcode,city,country,suburb,opening_hours,internet_access,wheelchair,phone,email,website,geometry,latitude,longitude
0,330264334,st. oberholz,rosenthaler straße,72,10119,berlin,de,mitte,"mo-th 08:00-24:00, fr 08:00-03:00, sa 09:00-03...",wlan,limited,+49 30 24085586,info@sanktoberholz.de,https://sanktoberholz.de/standorte/rosenthaler/,POINT (13.40178 52.52953),52.529530,13.401782
1,459659033,unknown,ella-kay-straße,38,10405,berlin,unknown,prenzlauer berg,unknown,unknown,unknown,unknown,unknown,unknown,POINT (13.4328 52.54017),52.540165,13.432801

In [ ]:
df_transformed.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   coworking_center_id  100 non-null    string
 1   name                 100 non-null    string
 2   street               100 non-null    string
 3   housenumber          100 non-null    string
 4   postcode             100 non-null    string
 5   city                 100 non-null    string
 6   country              100 non-null    string
 7   suburb               100 non-null    string
 8   opening_hours        100 non-null    string
 9   internet_access      100 non-null    string
 10  wheelchair           100 non-null    string
 11  phone                100 non-null    string
 12  email                100 non-null    string
 13  website              100 non-null    string
 14  geometry             100 non-null    geometry
 15  latitude             100 non-null    float64
 16  longitude            100 non-null    float64
dtypes: float64(2), geometry(1), string(14)
memory usage: 13.4 KB

In [156]:
import pandas as pd
from sqlalchemy import create_engine, text
import warnings

warnings.filterwarnings("ignore")

# Step 1: Neon DB connection string
DATABASE_URL = (
    "postgresql+psycopg2://neondb_owner:a9Am7Yy5r9_T7h4OF2GN@ep-falling-glitter-a5m0j5gk-pooler.us-east-2.aws.neon.tech:5432/neondb?sslmode=require"
)

# Step 2: Create engine
engine = create_engine(DATABASE_URL)

# Step 3: Drop old table if needed (be careful)
drop_sql = "DROP TABLE IF EXISTS test_berlin_data.coworking_centers_berlin;"
create_sql = """
CREATE TABLE test_berlin_data.coworking_centers_berlin (
    coworking_center_id TEXT PRIMARY KEY,
    name TEXT,
    street TEXT,
    housenumber TEXT,
    postcode TEXT,
    city TEXT,
    country TEXT,
    suburb TEXT,
    opening_hours TEXT,
    internet_access TEXT,
    wheelchair TEXT,
    phone TEXT,
    email TEXT,
    website TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION
);
"""

with engine.connect() as conn:
    conn.execute(text(drop_sql))
    conn.execute(text(create_sql))
    print("✅ Table recreated successfully with PK.")

# Step 4: Load DataFrame
df_final = pd.read_csv("/Users/ramzi.gossing/Webeet Project Folder/Webeet.io internship documentaion/layered-populate-data-pool-da/coworking_centers/sources_coworking_spaces/coworking_centers.csv")

# Step 5: Append data
df_final.to_sql(
    name="coworking_centers_berlin",
    con=engine,
    schema="test_berlin_data",
    if_exists="append",   # now safe to append
    index=False
)
print(f"✅ Inserted {len(df_final)} rows into DB.")

✅ Table recreated successfully with PK.
✅ Inserted 100 rows into DB.

**📥 2. Insert Clean DataFrame (df_final) into supermarkets_in_berlin Table**

In [157]:
# Assuming df_final is your cleaned and transformed DataFrame
df_final= pd.read_csv("/Users/ramzi.gossing/Webeet Project Folder/Webeet.io internship documentaion/layered-populate-data-pool-da/coworking_centers/sources_coworking_spaces/coworking_centers.csv")

df_final.to_sql(
    name="coworking_centers_berlin",
    con=engine,
    schema='test_berlin_data',
    if_exists="append",   # or "replace" or "fail" — use "append" in test phase
    index=False
)

100

**🧪 3. Optional — Validate Test Insert**

In [159]:
# Check if data was inserted
with engine.connect() as conn:
    count = conn.execute(text("SELECT COUNT(*) FROM test_berlin_data.coworking_centers_berlin")).scalar()
    print(f"✅ {count} rows in the DB.")

✅ 200 rows in the DB.